/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas3prak;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS A455LN
 */
public class no1modul3 extends javax.swing.JFrame {

    public no1modul3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        obatobatan = new javax.swing.ButtonGroup();
        pATAS = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pBAWAH = new javax.swing.JPanel();
        pembatalan = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        pilihobat = new javax.swing.JButton();
        pTENGAH = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        detail1 = new javax.swing.JButton();
        detail2 = new javax.swing.JButton();
        detail3 = new javax.swing.JButton();
        detail4 = new javax.swing.JButton();
        detail5 = new javax.swing.JButton();
        detail6 = new javax.swing.JButton();
        detail7 = new javax.swing.JButton();
        detail8 = new javax.swing.JButton();
        detail9 = new javax.swing.JButton();
        detail = new javax.swing.JButton();
        bodrex = new javax.swing.JRadioButton();
        tolakangin = new javax.swing.JRadioButton();
        samobyon = new javax.swing.JRadioButton();
        promaag = new javax.swing.JRadioButton();
        panadol = new javax.swing.JRadioButton();
        napacin = new javax.swing.JRadioButton();
        komik = new javax.swing.JRadioButton();
        insto = new javax.swing.JRadioButton();
        hufagrip = new javax.swing.JRadioButton();
        entrostop = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        gejalapenyakit = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pATAS.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS A455LN\\Downloads\\Logo-Apotek- kecil.png")); // NOI18N
        pATAS.add(jLabel1);

        jLabel2.setBackground(new java.awt.Color(0, 204, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 204, 0));
        jLabel2.setText("APOTEK SUKA SEHAT");
        pATAS.add(jLabel2);

        getContentPane().add(pATAS, java.awt.BorderLayout.PAGE_START);

        pBAWAH.setLayout(new java.awt.GridLayout(1, 0));

        pembatalan.setBackground(new java.awt.Color(153, 0, 0));
        pembatalan.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        pembatalan.setForeground(new java.awt.Color(255, 255, 255));
        pembatalan.setText("BATAL");
        pembatalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembatalanActionPerformed(evt);
            }
        });
        pBAWAH.add(pembatalan);

        reset.setBackground(new java.awt.Color(204, 204, 0));
        reset.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        pBAWAH.add(reset);

        pilihobat.setBackground(new java.awt.Color(0, 153, 0));
        pilihobat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pilihobat.setForeground(new java.awt.Color(255, 255, 255));
        pilihobat.setText("PILIH OBAT");
        pilihobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihobatActionPerformed(evt);
            }
        });
        pBAWAH.add(pilihobat);

        getContentPane().add(pBAWAH, java.awt.BorderLayout.PAGE_END);

        pTENGAH.setBackground(new java.awt.Color(204, 204, 204));
        pTENGAH.setLayout(new java.awt.GridBagLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS A455LN\\Downloads\\147272_10-5-2022_14-56-39-1665791232-removebg-preview kecil.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(jLabel3, gridBagConstraints);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS A455LN\\Downloads\\promaagkecil.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(jLabel4, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS A455LN\\Downloads\\panadolkecil.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(jLabel5, gridBagConstraints);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS A455LN\\Downloads\\tolakanginkecil.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(jLabel6, gridBagConstraints);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS A455LN\\Downloads\\neonapacinkecil.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(jLabel7, gridBagConstraints);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS A455LN\\Downloads\\samobyonkecil.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 35;
        pTENGAH.add(jLabel8, gridBagConstraints);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS A455LN\\Downloads\\komikkecil.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(jLabel9, gridBagConstraints);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS A455LN\\Downloads\\hufagripkecil.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(jLabel10, gridBagConstraints);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS A455LN\\Downloads\\instokecil.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(jLabel11, gridBagConstraints);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS A455LN\\Downloads\\entrostopkecil.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(jLabel12, gridBagConstraints);

        detail1.setBackground(new java.awt.Color(255, 255, 153));
        detail1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        detail1.setForeground(new java.awt.Color(51, 204, 0));
        detail1.setText("DETAIL");
        detail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detail1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(detail1, gridBagConstraints);

        detail2.setBackground(new java.awt.Color(255, 255, 153));
        detail2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        detail2.setForeground(new java.awt.Color(51, 204, 0));
        detail2.setText("DETAIL");
        detail2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detail2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(detail2, gridBagConstraints);

        detail3.setBackground(new java.awt.Color(255, 255, 153));
        detail3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        detail3.setForeground(new java.awt.Color(51, 204, 0));
        detail3.setText("DETAIL");
        detail3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detail3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(detail3, gridBagConstraints);

        detail4.setBackground(new java.awt.Color(255, 255, 153));
        detail4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        detail4.setForeground(new java.awt.Color(51, 204, 0));
        detail4.setText("DETAIL");
        detail4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detail4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(detail4, gridBagConstraints);

        detail5.setBackground(new java.awt.Color(255, 255, 153));
        detail5.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        detail5.setForeground(new java.awt.Color(51, 204, 0));
        detail5.setText("DETAIL");
        detail5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detail5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(detail5, gridBagConstraints);

        detail6.setBackground(new java.awt.Color(255, 255, 153));
        detail6.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        detail6.setForeground(new java.awt.Color(51, 204, 0));
        detail6.setText("DETAIL");
        detail6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detail6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(detail6, gridBagConstraints);

        detail7.setBackground(new java.awt.Color(255, 255, 153));
        detail7.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        detail7.setForeground(new java.awt.Color(51, 204, 0));
        detail7.setText("DETAIL");
        detail7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detail7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(detail7, gridBagConstraints);

        detail8.setBackground(new java.awt.Color(255, 255, 153));
        detail8.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        detail8.setForeground(new java.awt.Color(51, 204, 0));
        detail8.setText("DETAIL");
        detail8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detail8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(detail8, gridBagConstraints);

        detail9.setBackground(new java.awt.Color(255, 255, 153));
        detail9.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        detail9.setForeground(new java.awt.Color(51, 204, 0));
        detail9.setText("DETAIL");
        detail9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detail9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(detail9, gridBagConstraints);

        detail.setBackground(new java.awt.Color(255, 255, 153));
        detail.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        detail.setForeground(new java.awt.Color(51, 204, 0));
        detail.setText("DETAIL");
        detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(detail, gridBagConstraints);

        obatobatan.add(bodrex);
        bodrex.setForeground(new java.awt.Color(0, 0, 0));
        bodrex.setText("Bodrex");
        bodrex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodrexActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(bodrex, gridBagConstraints);

        obatobatan.add(tolakangin);
        tolakangin.setForeground(new java.awt.Color(0, 0, 0));
        tolakangin.setText("Tolakangin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(tolakangin, gridBagConstraints);

        obatobatan.add(samobyon);
        samobyon.setForeground(new java.awt.Color(0, 0, 0));
        samobyon.setText("Samobyon");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(samobyon, gridBagConstraints);

        obatobatan.add(promaag);
        promaag.setForeground(new java.awt.Color(0, 0, 0));
        promaag.setText("Promaag");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(promaag, gridBagConstraints);

        obatobatan.add(panadol);
        panadol.setForeground(new java.awt.Color(0, 0, 0));
        panadol.setText("Panadol");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(panadol, gridBagConstraints);

        obatobatan.add(napacin);
        napacin.setForeground(new java.awt.Color(0, 0, 0));
        napacin.setText("Napacin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(napacin, gridBagConstraints);

        obatobatan.add(komik);
        komik.setForeground(new java.awt.Color(0, 0, 0));
        komik.setText("Komik");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(komik, gridBagConstraints);

        obatobatan.add(insto);
        insto.setForeground(new java.awt.Color(0, 0, 0));
        insto.setText("Insto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(insto, gridBagConstraints);

        obatobatan.add(hufagrip);
        hufagrip.setForeground(new java.awt.Color(0, 0, 0));
        hufagrip.setText("Hufagrip");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(hufagrip, gridBagConstraints);

        obatobatan.add(entrostop);
        entrostop.setForeground(new java.awt.Color(0, 0, 0));
        entrostop.setText("Entrostop");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.ipadx = 22;
        pTENGAH.add(entrostop, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("GEJALA : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        pTENGAH.add(jLabel14, gridBagConstraints);

        gejalapenyakit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Gejala-", "Sakit Kepala", "Masuk Angin", "Kurang darah/Anemia", "Maag", "Migrain", "Sesak Nafas", "Batuk Berdahak", "Iritasi Mata", "Batuk untuk anak-anak", "Diare" }));
        gejalapenyakit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gejalapenyakitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pTENGAH.add(gejalapenyakit, gridBagConstraints);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pTENGAH.add(jPanel1, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pTENGAH.add(jPanel2, new java.awt.GridBagConstraints());

        getContentPane().add(pTENGAH, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pilihobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihobatActionPerformed
        // TODO add your handling code here:
        int hargabodrex = 19000;
        int hargatolakangin = 30000;
        int hargasamobyon = 15000;
        int hargapromaag = 23000;
        int hargapanadol = 26800;
        int harganapacin = 22000;
        int hargakomik = 10000;
        int hargainsto = 17000;
        int hargahufagrip = 24000;
        int hargaentrostop = 18500;
        
        if (bodrex.isSelected()) {
            JOptionPane.showMessageDialog(this, 
            "Anda memilih: Bodrex \nHarga: " + hargabodrex + " IDR" + "\nSilahkan bawa Struk ini ke kasir untuk mengambil obat dan Pembayaran", 
            "Struk Pembelian", JOptionPane.INFORMATION_MESSAGE);
        } else if (tolakangin.isSelected()) {
            JOptionPane.showMessageDialog(this, 
            "Anda memilih: Tolak Angin \nHarga: " + hargatolakangin + " IDR" + "\nSilahkan bawa Struk ini ke kasir untuk mengambil obat dan Pembayaran", 
            "Struk Pembelian", JOptionPane.INFORMATION_MESSAGE);
        } else if (samobyon.isSelected()) {
            JOptionPane.showMessageDialog(this, 
            "Anda memilih: Samobyon \nHarga: " + hargasamobyon + " IDR" + "\nSilahkan bawa Struk ini ke kasir untuk mengambil obat dan Pembayaran", 
            "Struk Pembelian", JOptionPane.INFORMATION_MESSAGE);
        } else if (promaag.isSelected()) {
            JOptionPane.showMessageDialog(this, 
            "Anda memilih: Promaag \nHarga: " + hargapromaag + " IDR" + "\nSilahkan bawa Struk ini ke kasir untuk mengambil obat dan Pembayaran", 
            "Struk Pembelian", JOptionPane.INFORMATION_MESSAGE);
        } else if (panadol.isSelected()) {
            JOptionPane.showMessageDialog(this, 
            "Anda memilih: Panadol \nHarga: " + hargapanadol + " IDR" + "\nSilahkan bawa Struk ini ke kasir untuk mengambil obat dan Pembayaran", 
            "Struk Pembelian", JOptionPane.INFORMATION_MESSAGE);
        } else if (napacin.isSelected()) {
            JOptionPane.showMessageDialog(this, 
            "Anda memilih: Napacin \nHarga: " + harganapacin + " IDR" + "\nSilahkan bawa Struk ini ke kasir untuk mengambil obat dan Pembayaran", 
            "Struk Pembelian", JOptionPane.INFORMATION_MESSAGE);
        } else if (komik.isSelected()) {
            JOptionPane.showMessageDialog(this, 
            "Anda memilih: Komik \nHarga: " + hargakomik + " IDR" + "\nSilahkan bawa Struk ini ke kasir untuk mengambil obat dan Pembayaran", 
            "Struk Pembelian", JOptionPane.INFORMATION_MESSAGE);
        } else if (insto.isSelected()) {
            JOptionPane.showMessageDialog(this, 
            "Anda memilih: Insto \nHarga: " + hargainsto + " IDR" + "\nSilahkan bawa Struk ini ke kasir untuk mengambil obat dan Pembayaran", 
            "Struk Pembelian", JOptionPane.INFORMATION_MESSAGE);
        } else if (hufagrip.isSelected()) {
            JOptionPane.showMessageDialog(this, 
            "Anda memilih: Hufagrip\nHarga: " + hargahufagrip + " IDR" + "\nSilahkan bawa Struk ini ke kasir untuk mengambil obat dan Pembayaran", 
            "Struk Pembelian", JOptionPane.INFORMATION_MESSAGE);
        } else if (entrostop.isSelected()) {
            JOptionPane.showMessageDialog(this, 
            "Anda memilih: Entrostop\nHarga: " + hargaentrostop + " IDR" + "\nSilahkan bawa Struk ini ke kasir untuk mengambil obat dan Pembayaran", 
            "Struk Pembelian", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Silakan pilih obat yang tersedia sebelum melanjutkan", "Struk Pembelian",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_pilihobatActionPerformed

    private void pembatalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembatalanActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this,"ingin membatalkan dan keluar?","Konfirmasi Pembatalan",JOptionPane.YES_NO_OPTION);
         
        if (option == JOptionPane.YES_OPTION) {
        JOptionPane.showMessageDialog(this,"Terimakasih Telah Mencoba Layanan Kami","Pesan",JOptionPane.INFORMATION_MESSAGE);
        System.exit(0); 
        }
    }//GEN-LAST:event_pembatalanActionPerformed

    private void detail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detail1ActionPerformed
        // TODO add your handling code here:
        String detailObat = "Nama: Bodrex\nKegunaan: Mengatasi sakit kepala dan demam\nDosis: 1 tablet 3 kali sehari\nHarga : Rp 19.000";
        JOptionPane.showMessageDialog(this, detailObat, "Detail Obat", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_detail1ActionPerformed

    private void detail2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detail2ActionPerformed
        // TODO add your handling code here:
        String detailObat = "Nama: Tolakangin\nKegunaan: Meredakan masuk angin dan meningkatkan imun tubuh\nDosis: 1 sachet 2 kali sehari\nHarga : Rp 30.000";
        JOptionPane.showMessageDialog(this, detailObat, "Detail Obat", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_detail2ActionPerformed

    private void detail3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detail3ActionPerformed
        // TODO add your handling code here:
        String detailObat = "Nama: Samobyon\nKegunaan: Menambah darah untuk penderita darah rendah \nDosis: 1 tablet 1 kali sehari\nHarga : Rp 15.000";
        JOptionPane.showMessageDialog(this, detailObat, "Detail Obat", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_detail3ActionPerformed

    private void detail4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detail4ActionPerformed
        // TODO add your handling code here:
        String detailObat = "Nama: Promaag\nKegunaan: Mengatasi maag dan nyeri lambung\nDosis: 1 sachet 2 kali sehari\nHarga : Rp 23.000";
        JOptionPane.showMessageDialog(this, detailObat, "Detail Obat", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_detail4ActionPerformed

    private void detail5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detail5ActionPerformed
        // TODO add your handling code here:
        String detailObat = "Nama: Panadol\nKegunaan: Mengurangi sakit kepala sebelah atau migrain \nDosis: 1 tablet 3 kali sehari\nHarga : Rp 26.800";
        JOptionPane.showMessageDialog(this, detailObat, "Detail Obat", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_detail5ActionPerformed

    private void detail6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detail6ActionPerformed
        // TODO add your handling code here
        String detailObat = "Nama: Napacin\nKegunaan: Mengobati sesak nafas dan meredakan asma yang kambuh\nDosis: 1 tablet 2 kali sehari\nHarga : Rp 22.000";
        JOptionPane.showMessageDialog(this, detailObat, "Detail Obat", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_detail6ActionPerformed

    private void detail7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detail7ActionPerformed
        // TODO add your handling code here:
        String detailObat = "Nama: Komik\nKegunaan: Meredakan batuk berdahak\nDosis: 1 tablet 3 kali sehari\nHarga : Rp 10.000";
        JOptionPane.showMessageDialog(this, detailObat, "Detail Obat", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_detail7ActionPerformed

    private void detail8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detail8ActionPerformed
        // TODO add your handling code here:
        String detailObat = "Nama: Insto\nKegunaan: Mengatasi mata merah dan iritasi\nDosis: Teteskan 2-3 kali sehari\nHarga : Rp 17.000";
        JOptionPane.showMessageDialog(this, detailObat, "Detail Obat", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_detail8ActionPerformed

    private void detail9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detail9ActionPerformed
        // TODO add your handling code here:
        String detailObat = "Nama: Hufagrip\nKegunaan: Mengobati flu dan batuk untuk anak kecil dibawah 14tahun \nDosis: 1 tablet 3 kali sehari\nHarga : Rp 24.000";
        JOptionPane.showMessageDialog(this, detailObat, "Detail Obat", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_detail9ActionPerformed

    private void detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailActionPerformed
        // TODO add your handling code here:
        String detailObat = "Nama: Entrostop\nKegunaan: Mengobati diare \nDosis: 2 tablet setelah buang air besar\nHarga : Rp 18.500";
        JOptionPane.showMessageDialog(this, detailObat, "Detail Obat", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_detailActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        gejalapenyakit.setSelectedIndex(0);
        obatobatan.clearSelection();
    }//GEN-LAST:event_resetActionPerformed

    private void gejalapenyakitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gejalapenyakitActionPerformed
        // TODO add your handling code here:
        String gejala = (String) gejalapenyakit.getSelectedItem();
    
        if ("Sakit Kepala".equals(gejala)) {        
        JOptionPane.showMessageDialog(this, "Rekomendasi obat : Bodrex\nSilahkan Pilih Di Menu Bawah!", "Obat Rekomendasi", JOptionPane.INFORMATION_MESSAGE);
        bodrex.setSelected(true);
        } else if ("Masuk Angin".equals(gejala)) {
        JOptionPane.showMessageDialog(this, "Rekomendasi obat : TolakAngin\nSilahkan Pilih Di Menu Bawah!", "Obat Rekomendasi", JOptionPane.INFORMATION_MESSAGE);
        tolakangin.setSelected(true);
        } else if ("Kurang darah/Anemia".equals(gejala)) {
        JOptionPane.showMessageDialog(this, "Rekomendasi obat : Samobyon\nSilahkan Pilih Di Menu Bawah!", "Obat Rekomendasi", JOptionPane.INFORMATION_MESSAGE);
        samobyon.setSelected(true);
        } else if ("Maag".equals(gejala)) {
        JOptionPane.showMessageDialog(this, "Rekomendasi obat :  Promaag\nSilahkan Pilih D          i Menu Bawah!", "Obat Rekomendasi", JOptionPane.INFORMATION_MESSAGE);
        promaag.setSelected(true);
        } else if ("Migrain".equals(gejala)) {
        JOptionPane.showMessageDialog(this, "Rekomendasi obat :  Panadol\nSilahkan Pilih Di Menu Bawah!", "Obat Rekomendasi", JOptionPane.INFORMATION_MESSAGE);
        panadol.setSelected(true);
        } else if ("Sesak Nafas".equals(gejala)) {
        JOptionPane.showMessageDialog(this, "Rekomendasi obat :  Napacin\nSilahkan Pilih Di Menu Bawah!", "Obat Rekomendasi", JOptionPane.INFORMATION_MESSAGE);
        napacin.setSelected(true);
        } else if ("Batuk Berdahak".equals(gejala)) {
        JOptionPane.showMessageDialog(this, "Rekomendasi obat :  Komik\nSilahkan Pilih Di Menu Bawah!", "Obat Rekomendasi", JOptionPane.INFORMATION_MESSAGE);
        komik.setSelected(true);
        } else if ("Iritasi Mata".equals(gejala)) {
        JOptionPane.showMessageDialog(this, "Rekomendasi obat :  Insto\nSilahkan Pilih Di Menu Bawah!", "Obat Rekomendasi", JOptionPane.INFORMATION_MESSAGE);
        insto.setSelected(true);
        } else if ("Batuk untuk anak-anak".equals(gejala)) {
        JOptionPane.showMessageDialog(this, "Rekomendasi obat :  Hufagrip\nSilahkan Pilih Di Menu Bawah!", "Obat Rekomendasi", JOptionPane.INFORMATION_MESSAGE);
        hufagrip.setSelected(true);
        } else if ("Diare".equals(gejala)) {
        JOptionPane.showMessageDialog(this, "Rekomendasi obat :  Entrostop\nSilahkan Pilih Di Menu Bawah!", "Obat Rekomendasi", JOptionPane.INFORMATION_MESSAGE);
        entrostop.setSelected(true);
        }
    }//GEN-LAST:event_gejalapenyakitActionPerformed

    private void bodrexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodrexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bodrexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(no1modul3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(no1modul3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(no1modul3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(no1modul3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new no1modul3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bodrex;
    private javax.swing.JButton detail;
    private javax.swing.JButton detail1;
    private javax.swing.JButton detail2;
    private javax.swing.JButton detail3;
    private javax.swing.JButton detail4;
    private javax.swing.JButton detail5;
    private javax.swing.JButton detail6;
    private javax.swing.JButton detail7;
    private javax.swing.JButton detail8;
    private javax.swing.JButton detail9;
    private javax.swing.JRadioButton entrostop;
    private javax.swing.JComboBox<String> gejalapenyakit;
    private javax.swing.JRadioButton hufagrip;
    private javax.swing.JRadioButton insto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton komik;
    private javax.swing.JRadioButton napacin;
    private javax.swing.ButtonGroup obatobatan;
    private javax.swing.JPanel pATAS;
    private javax.swing.JPanel pBAWAH;
    private javax.swing.JPanel pTENGAH;
    private javax.swing.JRadioButton panadol;
    private javax.swing.JButton pembatalan;
    private javax.swing.JButton pilihobat;
    private javax.swing.JRadioButton promaag;
    private javax.swing.JButton reset;
    private javax.swing.JRadioButton samobyon;
    private javax.swing.JRadioButton tolakangin;
    // End of variables declaration//GEN-END:variables
}
