/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas2;

import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class tugas2 extends javax.swing.JFrame {

    DecimalFormat formatter = new DecimalFormat(",###");    
    HashMap<String, DataMahasiswa> dataSiswa = new HashMap<>();

    public tugas2() {
        initComponents();
        
        DataMahasiswa mhs1 = new DataMahasiswa("230441100037", "Nur Muhammad", "Sistem Informasi", 500000);
        mhs1.setPembayaranBulan("January", "lunas", "02-01-2024");
        mhs1.setPembayaranBulan("February", "lunas", "05-02-2024");
        mhs1.setPembayaranBulan("October", "lunas", "05-10-2024");
        dataSiswa.put("230441100037", mhs1);
        
        DataMahasiswa mhs2 = new DataMahasiswa("230441100060", "Akbar Maulana", "Sistem Informasi", 500000);
        mhs2.setPembayaranBulan("January", "lunas", "02-01-2024");
        mhs2.setPembayaranBulan("February", "lunas", "05-02-2024");
        mhs2.setPembayaranBulan("October", "lunas", "05-10-2024");
        dataSiswa.put("230441100060", mhs2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        inputNIM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dataNama = new javax.swing.JLabel();
        dataNIM = new javax.swing.JLabel();
        dataStatusSPP = new javax.swing.JLabel();
        dataSPP = new javax.swing.JLabel();
        CariNim = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        dataProdi = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HistoriBayar = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        January = new javax.swing.JCheckBox();
        February = new javax.swing.JCheckBox();
        March = new javax.swing.JCheckBox();
        April = new javax.swing.JCheckBox();
        May = new javax.swing.JCheckBox();
        June = new javax.swing.JCheckBox();
        July = new javax.swing.JCheckBox();
        August = new javax.swing.JCheckBox();
        September = new javax.swing.JCheckBox();
        October = new javax.swing.JCheckBox();
        November = new javax.swing.JCheckBox();
        December = new javax.swing.JCheckBox();
        tot = new javax.swing.JLabel();
        TotalBayar = new javax.swing.JTextField();
        tot1 = new javax.swing.JLabel();
        Cash = new javax.swing.JTextField();
        Bayar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(53, 21, 235));

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Aplikasi Pembayaran SPP ");
        jPanel1.add(jLabel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Masukkan NIM : ");

        inputNIM.setBackground(new java.awt.Color(255, 255, 255));
        inputNIM.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nama              : ");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("NIM                 :");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("SPP perbulan :");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Status SPP     :");

        dataNama.setText(" ");

        dataNIM.setText(" ");

        dataStatusSPP.setText(" ");

        dataSPP.setText(" ");

        CariNim.setText("Submit");
        CariNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariNimActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Prodi               :");

        dataProdi.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataSPP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(5, 5, 5))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataStatusSPP, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataNama, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CariNim)
                        .addGap(52, 52, 52))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dataNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(inputNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CariNim, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dataNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dataNIM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(dataProdi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dataSPP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(dataStatusSPP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {inputNIM, jLabel2});

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Histori Pembayaran SPP");

        HistoriBayar.setBackground(new java.awt.Color(255, 255, 255));
        HistoriBayar.setColumns(20);
        HistoriBayar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        HistoriBayar.setForeground(new java.awt.Color(0, 0, 0));
        HistoriBayar.setRows(5);
        HistoriBayar.setBorder(null);
        HistoriBayar.setDragEnabled(true);
        HistoriBayar.setFocusable(false);
        HistoriBayar.setRequestFocusEnabled(false);
        HistoriBayar.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(HistoriBayar);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Bayaran SPP");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Bulan :");

        January.setBackground(new java.awt.Color(255, 255, 255));
        January.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        January.setForeground(new java.awt.Color(0, 0, 0));
        January.setText("January");
        January.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JanuaryActionPerformed(evt);
            }
        });

        February.setBackground(new java.awt.Color(255, 255, 255));
        February.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        February.setForeground(new java.awt.Color(0, 0, 0));
        February.setText("February");
        February.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FebruaryActionPerformed(evt);
            }
        });

        March.setBackground(new java.awt.Color(255, 255, 255));
        March.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        March.setForeground(new java.awt.Color(0, 0, 0));
        March.setText("March");
        March.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarchActionPerformed(evt);
            }
        });

        April.setBackground(new java.awt.Color(255, 255, 255));
        April.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        April.setForeground(new java.awt.Color(0, 0, 0));
        April.setText("April");
        April.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AprilActionPerformed(evt);
            }
        });

        May.setBackground(new java.awt.Color(255, 255, 255));
        May.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        May.setForeground(new java.awt.Color(0, 0, 0));
        May.setText("May");
        May.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MayActionPerformed(evt);
            }
        });

        June.setBackground(new java.awt.Color(255, 255, 255));
        June.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        June.setForeground(new java.awt.Color(0, 0, 0));
        June.setText("June");
        June.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JuneActionPerformed(evt);
            }
        });

        July.setBackground(new java.awt.Color(255, 255, 255));
        July.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        July.setForeground(new java.awt.Color(0, 0, 0));
        July.setText("July");
        July.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JulyActionPerformed(evt);
            }
        });

        August.setBackground(new java.awt.Color(255, 255, 255));
        August.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        August.setForeground(new java.awt.Color(0, 0, 0));
        August.setText("August");
        August.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AugustActionPerformed(evt);
            }
        });

        September.setBackground(new java.awt.Color(255, 255, 255));
        September.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        September.setForeground(new java.awt.Color(0, 0, 0));
        September.setText("September");
        September.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeptemberActionPerformed(evt);
            }
        });

        October.setBackground(new java.awt.Color(255, 255, 255));
        October.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        October.setForeground(new java.awt.Color(0, 0, 0));
        October.setText("October");
        October.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OctoberActionPerformed(evt);
            }
        });

        November.setBackground(new java.awt.Color(255, 255, 255));
        November.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        November.setForeground(new java.awt.Color(0, 0, 0));
        November.setText("November");
        November.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovemberActionPerformed(evt);
            }
        });

        December.setBackground(new java.awt.Color(255, 255, 255));
        December.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        December.setForeground(new java.awt.Color(0, 0, 0));
        December.setText("December");
        December.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecemberActionPerformed(evt);
            }
        });

        tot.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        tot.setForeground(new java.awt.Color(0, 0, 0));
        tot.setText("Total Bayar :");

        TotalBayar.setBackground(new java.awt.Color(255, 255, 255));
        TotalBayar.setForeground(new java.awt.Color(0, 0, 0));
        TotalBayar.setFocusable(false);
        TotalBayar.setRequestFocusEnabled(false);
        TotalBayar.setVerifyInputWhenFocusTarget(false);

        tot1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        tot1.setForeground(new java.awt.Color(0, 0, 0));
        tot1.setText("Cash :");

        Cash.setBackground(new java.awt.Color(255, 255, 255));
        Cash.setForeground(new java.awt.Color(0, 0, 0));

        Bayar.setText("Bayar");
        Bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TotalBayar)
                    .addComponent(Cash)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tot)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(January)
                                    .addComponent(February)
                                    .addComponent(March)
                                    .addComponent(April)
                                    .addComponent(May)
                                    .addComponent(June))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(December)
                                    .addComponent(November)
                                    .addComponent(October)
                                    .addComponent(September)
                                    .addComponent(August)
                                    .addComponent(July)))
                            .addComponent(tot1)
                            .addComponent(Bayar))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {April, August, December, February, January, July, June, March, May, November, October, September});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(January)
                    .addComponent(July))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(February)
                    .addComponent(August))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(March)
                    .addComponent(September))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(April)
                    .addComponent(October))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(May)
                    .addComponent(November))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(June)
                    .addComponent(December))
                .addGap(18, 18, 18)
                .addComponent(tot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tot1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bayar)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {April, August, December, February, January, July, June, March, May, November, October, September});

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CariNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariNimActionPerformed
        cekDataSiswa(inputNIM.getText());
    }//GEN-LAST:event_CariNimActionPerformed

    private void JanuaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JanuaryActionPerformed
        pilihBulan();
    }//GEN-LAST:event_JanuaryActionPerformed
    private void FebruaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FebruaryActionPerformed
        pilihBulan();
    }//GEN-LAST:event_FebruaryActionPerformed
    private void MarchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarchActionPerformed
        pilihBulan();
    }//GEN-LAST:event_MarchActionPerformed
    private void AprilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AprilActionPerformed
        pilihBulan();
    }//GEN-LAST:event_AprilActionPerformed
    private void MayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MayActionPerformed
        pilihBulan();
    }//GEN-LAST:event_MayActionPerformed
    private void JuneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JuneActionPerformed
        pilihBulan();
    }//GEN-LAST:event_JuneActionPerformed
    private void JulyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JulyActionPerformed
        pilihBulan();
    }//GEN-LAST:event_JulyActionPerformed
    private void AugustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AugustActionPerformed
        pilihBulan();
    }//GEN-LAST:event_AugustActionPerformed
    private void SeptemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeptemberActionPerformed
        pilihBulan();
    }//GEN-LAST:event_SeptemberActionPerformed
    private void OctoberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OctoberActionPerformed
        pilihBulan();
    }//GEN-LAST:event_OctoberActionPerformed
    private void NovemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovemberActionPerformed
        pilihBulan();
    }//GEN-LAST:event_NovemberActionPerformed
    private void DecemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecemberActionPerformed
        pilihBulan();
    }//GEN-LAST:event_DecemberActionPerformed

    private void BayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayarActionPerformed
        hitungBayar();
    }//GEN-LAST:event_BayarActionPerformed
    
    private void pilihBulan() {
        int spp = Integer.parseInt(dataSPP.getText()
                .replace("Rp", "")
                .replace("/bulan", "")
                .replace(",", "")
                .trim()
            );
        
        int total = 0;
        total+= January.isSelected() ? spp : 0;
        total+= February.isSelected() ? spp : 0;
        total+= March.isSelected() ? spp : 0;
        total+= April.isSelected() ? spp : 0;
        total+= May.isSelected() ? spp : 0;
        total+= June.isSelected() ? spp : 0;
        total+= July.isSelected() ? spp : 0;
        total+= August.isSelected() ? spp : 0;
        total+= September.isSelected() ? spp : 0;
        total+= October.isSelected() ? spp : 0;
        total+= November.isSelected() ? spp : 0;
        total+= December.isSelected() ? spp : 0;
        TotalBayar.setText("Rp." + formatter.format(total));        
    }
    
    private void cekDataSiswa(String nim) {
        DataMahasiswa siswa = dataSiswa.get(nim);
        
        January.setSelected(false);
        February.setSelected(false);
        March.setSelected(false);
        April.setSelected(false);
        May.setSelected(false);
        June.setSelected(false);
        July.setSelected(false);
        August.setSelected(false);
        September.setSelected(false);
        October.setSelected(false);
        November.setSelected(false);
        December.setSelected(false);
        Cash.setText("");
        TotalBayar.setText("");

        if (siswa != null) {
            dataNIM.setText(siswa.getNim());
            dataNama.setText(siswa.getNama());
            dataProdi.setText(siswa.getProdi());
            dataSPP.setText("Rp " + formatter.format(siswa.getSpp()) + "/bulan");
            dataStatusSPP.setText(siswa.getStatusPembayaran());

            String dataBayar = "";
            for (String bulan : siswa.getPembayaranBulan().keySet()) {
                String[] status = siswa.getPembayaranBulan().get(bulan);
                dataBayar += " - " 
                    + bulan + "\t| " 
                    + status[0] + " | " 
                    + (status[1].isEmpty() ? "-" : status[1])
                    +"\n";
                
                if (bulan.equalsIgnoreCase("January") && !status[1].isEmpty()) January.setEnabled(false);
                if (bulan.equalsIgnoreCase("February") && !status[1].isEmpty()) February.setEnabled(false);
                if (bulan.equalsIgnoreCase("March") && !status[1].isEmpty()) March.setEnabled(false);
                if (bulan.equalsIgnoreCase("April") && !status[1].isEmpty()) April.setEnabled(false);
                if (bulan.equalsIgnoreCase("May") && !status[1].isEmpty()) May.setEnabled(false);
                if (bulan.equalsIgnoreCase("June") && !status[1].isEmpty()) June.setEnabled(false);
                if (bulan.equalsIgnoreCase("July") && !status[1].isEmpty()) July.setEnabled(false);
                if (bulan.equalsIgnoreCase("August") && !status[1].isEmpty()) August.setEnabled(false);
                if (bulan.equalsIgnoreCase("September") && !status[1].isEmpty()) September.setEnabled(false);
                if (bulan.equalsIgnoreCase("October") && !status[1].isEmpty()) October.setEnabled(false);
                if (bulan.equalsIgnoreCase("November") && !status[1].isEmpty()) November.setEnabled(false);
                if (bulan.equalsIgnoreCase("December") && !status[1].isEmpty()) December.setEnabled(false);
            }
            HistoriBayar.setText(dataBayar);
        } else {
            JOptionPane.showMessageDialog(this, "Data siswa dengan NIM tersebut tidak ditemukan!");
        }
    }
    
    private void hitungBayar() {
        try {
            int cash = 
                (Cash.getText().isEmpty())
                    ? 0 
                    : Integer.parseInt(Cash.getText()
                        .replace(",", "")
                        .replace(".", "")
                    );
            int total = 
                (TotalBayar.getText().isEmpty())
                    ? 0 
                    : Integer.parseInt(TotalBayar.getText()
                        .replace(",", "")
                        .replace(".", "")
                        .replace("Rp", "")
                    );
            if (cash != 0 && total != 0) {
                if (cash < total) {
                    JOptionPane.showMessageDialog(null, "Uang anda tidak cukup!", "Peringatan", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                int pilihan = JOptionPane.showConfirmDialog(null, "Anda yakin ingin membayar?", "peringatan", JOptionPane.YES_NO_OPTION);
                if (pilihan == JOptionPane.YES_OPTION) {
                    DataMahasiswa mhs = dataSiswa.get(inputNIM.getText());
                    
                    LocalDate ts = LocalDate.now();
                    DateTimeFormatter formatterTanggal = DateTimeFormatter.ofPattern("dd-MM-yyyy");
                    String tanggal = ts.format(formatterTanggal);
                    
                    JCheckBox[] bulans = {January, February, March, April, May, June, July, August, September, October, November, December};
                    for (int i = 0; i < bulans.length; i++) {
                        if(bulans[i].isSelected()) {
                            System.out.println(bulans[i].getText() + "---" + tanggal);
                            mhs.setPembayaranBulan(bulans[i].getText(), "lunas", tanggal);
                        }
                    }  
                    
                    String pesan = "Transaksi Berhasil" + (cash-total == 0 ? "" : ", Kembalian Rp." + formatter.format(cash-total));
                    JOptionPane.showMessageDialog(null, pesan, "Pesan", JOptionPane.PLAIN_MESSAGE);
                    cekDataSiswa(inputNIM.getText());
                    
                    January.setSelected(false);
                    February.setSelected(false);
                    March.setSelected(false);
                    April.setSelected(false);
                    May.setSelected(false);
                    June.setSelected(false);
                    July.setSelected(false);
                    August.setSelected(false);
                    September.setSelected(false);
                    October.setSelected(false);
                    November.setSelected(false);
                    December.setSelected(false);
                    Cash.setText("");
                    TotalBayar.setText("");
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Input harus berupa angka!", "Peringatan", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tugas2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox April;
    private javax.swing.JCheckBox August;
    private javax.swing.JButton Bayar;
    private javax.swing.JButton CariNim;
    private javax.swing.JTextField Cash;
    private javax.swing.JCheckBox December;
    private javax.swing.JCheckBox February;
    private javax.swing.JTextArea HistoriBayar;
    private javax.swing.JCheckBox January;
    private javax.swing.JCheckBox July;
    private javax.swing.JCheckBox June;
    private javax.swing.JCheckBox March;
    private javax.swing.JCheckBox May;
    private javax.swing.JCheckBox November;
    private javax.swing.JCheckBox October;
    private javax.swing.JCheckBox September;
    private javax.swing.JTextField TotalBayar;
    private javax.swing.JLabel dataNIM;
    private javax.swing.JLabel dataNama;
    private javax.swing.JLabel dataProdi;
    private javax.swing.JLabel dataSPP;
    private javax.swing.JLabel dataStatusSPP;
    private javax.swing.JTextField inputNIM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tot;
    private javax.swing.JLabel tot1;
    // End of variables declaration//GEN-END:variables
}
