import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DIKNAS
 */
public class TokoRoti extends javax.swing.JFrame {

    /**
     * Creates new form TokoRoti
     */
    DecimalFormat formatter = new DecimalFormat(",###");
    
    String textPesanan = "";
    String menuPesanan;
    String toppingPesanan;
    int totalSemua = 0;
    
    
    public TokoRoti() {
        initComponents();
        TFTotal.setText("0");
        TFTotalSemua.setText("0");
        Menu.clearSelection();
        Topping.clearSelection();
        BKurangJumlah.setEnabled(false);
        
        TPCoklat.setEnabled(false);
        TPKacang.setEnabled(false);
        TPKeju.setEnabled(false);
        TPMeses.setEnabled(false);
        
        Cash.setText("0");
        Kembalian.setText("0");
        TFJumlah.setText("1");
        TFJumlah.setHorizontalAlignment(JTextField.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.ButtonGroup();
        Topping = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        MRotiTawar = new javax.swing.JRadioButton();
        MRotiCoklat = new javax.swing.JRadioButton();
        MRotiIsi = new javax.swing.JRadioButton();
        MRotiPisang = new javax.swing.JRadioButton();
        MRotiGandum = new javax.swing.JRadioButton();
        MRotiKeju = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        TPMeses = new javax.swing.JRadioButton();
        TPKeju = new javax.swing.JRadioButton();
        TPCoklat = new javax.swing.JRadioButton();
        TPKacang = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        BTambahJumlah = new javax.swing.JButton();
        BKurangJumlah = new javax.swing.JButton();
        TFJumlah = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TFTotal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Cash = new javax.swing.JTextField();
        Kembalian = new javax.swing.JTextField();
        Reset = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        kurang = new javax.swing.JLabel();
        TambahPesanan = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        TFTotalSemua = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Pesanan = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Beli = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ROTI BAROKAH");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(538, 538, 538)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 153));
        jLabel7.setText("Menu Roti");

        Menu.add(MRotiTawar);
        MRotiTawar.setForeground(new java.awt.Color(0, 0, 0));
        MRotiTawar.setText("Roti Tawar - Rp.15.000");
        MRotiTawar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MRotiTawarActionPerformed(evt);
            }
        });

        Menu.add(MRotiCoklat);
        MRotiCoklat.setForeground(new java.awt.Color(0, 0, 0));
        MRotiCoklat.setText("Roti Coklat - Rp.18.000");
        MRotiCoklat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MRotiCoklatActionPerformed(evt);
            }
        });

        Menu.add(MRotiIsi);
        MRotiIsi.setForeground(new java.awt.Color(0, 0, 0));
        MRotiIsi.setText("Roti Isi - Rp.20.000");
        MRotiIsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MRotiIsiActionPerformed(evt);
            }
        });

        Menu.add(MRotiPisang);
        MRotiPisang.setForeground(new java.awt.Color(0, 0, 0));
        MRotiPisang.setText("Roti Pisang - Rp.23.000");
        MRotiPisang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MRotiPisangActionPerformed(evt);
            }
        });

        Menu.add(MRotiGandum);
        MRotiGandum.setForeground(new java.awt.Color(0, 0, 0));
        MRotiGandum.setText("Roti Gandum - Rp.17.000");
        MRotiGandum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MRotiGandumActionPerformed(evt);
            }
        });

        Menu.add(MRotiKeju);
        MRotiKeju.setForeground(new java.awt.Color(0, 0, 0));
        MRotiKeju.setText("Roti Keju - Rp.25.000");
        MRotiKeju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MRotiKejuActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 153));
        jLabel8.setText("Topping");

        Topping.add(TPMeses);
        TPMeses.setForeground(new java.awt.Color(0, 0, 0));
        TPMeses.setSelected(true);
        TPMeses.setText("Meses - Rp.4.000");
        TPMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPMesesActionPerformed(evt);
            }
        });

        Topping.add(TPKeju);
        TPKeju.setForeground(new java.awt.Color(0, 0, 0));
        TPKeju.setText("Keju - Rp.3.000");
        TPKeju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPKejuActionPerformed(evt);
            }
        });

        Topping.add(TPCoklat);
        TPCoklat.setForeground(new java.awt.Color(0, 0, 0));
        TPCoklat.setText("Coklat - Rp.5.000");
        TPCoklat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPCoklatActionPerformed(evt);
            }
        });

        Topping.add(TPKacang);
        TPKacang.setForeground(new java.awt.Color(0, 0, 0));
        TPKacang.setText("Kacang - Rp.4.000");
        TPKacang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPKacangActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 204, 153));
        jLabel10.setText("Jumlah");

        BTambahJumlah.setBackground(new java.awt.Color(255, 204, 153));
        BTambahJumlah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTambahJumlah.setText("+");
        BTambahJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahJumlahActionPerformed(evt);
            }
        });

        BKurangJumlah.setBackground(new java.awt.Color(255, 204, 153));
        BKurangJumlah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BKurangJumlah.setText("-");
        BKurangJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKurangJumlahActionPerformed(evt);
            }
        });

        TFJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFJumlahActionPerformed(evt);
            }
        });
        TFJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFJumlahKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 204, 153));
        jLabel11.setText("Total");

        TFTotal.setEditable(false);
        TFTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTotalActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 204, 153));
        jLabel13.setText("Cash");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 204, 153));
        jLabel14.setText("Kembalian");

        Cash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CashKeyReleased(evt);
            }
        });

        Kembalian.setEditable(false);

        Reset.setBackground(new java.awt.Color(255, 204, 153));
        Reset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        kurang.setText("  ");

        TambahPesanan.setBackground(new java.awt.Color(255, 204, 153));
        TambahPesanan.setText("Tambah Pesanan");
        TambahPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahPesananActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 204, 153));
        jLabel12.setText("Total Semua");

        TFTotalSemua.setEditable(false);
        TFTotalSemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTotalSemuaActionPerformed(evt);
            }
        });

        Pesanan.setEditable(false);
        Pesanan.setColumns(20);
        Pesanan.setRows(5);
        jScrollPane1.setViewportView(Pesanan);

        jPanel3.setBackground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Roti Tawar.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Roti Gandum.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Roti Isi.jpg"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Roti Keju.jpg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Roti Pisang.jpg"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Roti Coklat.jpg"))); // NOI18N

        Beli.setText("Beli");
        Beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MRotiCoklat, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MRotiTawar, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MRotiKeju, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(MRotiGandum, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(MRotiPisang))
                            .addComponent(MRotiIsi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TPMeses)
                        .addGap(29, 29, 29)
                        .addComponent(TPKeju, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(TPCoklat)
                        .addGap(29, 29, 29)
                        .addComponent(TPKacang)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(TFTotalSemua, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kurang, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TambahPesanan)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BKurangJumlah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TFJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(jLabel11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTambahJumlah)
                                .addGap(124, 124, 124)
                                .addComponent(TFTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Cash, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Beli)
                                    .addGap(30, 30, 30)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(Kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Reset))
                .addGap(93, 93, 93))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Cash, Kembalian, TFTotal});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {TPCoklat, TPKacang, TPKeju, TPMeses});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {MRotiCoklat, MRotiGandum, MRotiIsi, MRotiPisang, MRotiTawar});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BKurangJumlah, BTambahJumlah});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel5, jLabel6, jLabel9});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TFJumlah)
                                    .addComponent(BKurangJumlah)
                                    .addComponent(BTambahJumlah)
                                    .addComponent(TFTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TambahPesanan)
                                .addGap(451, 451, 451)
                                .addComponent(Reset)
                                .addContainerGap())
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TFTotalSemua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Cash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Beli))
                                .addGap(2, 2, 2)
                                .addComponent(kurang))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel7)
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(MRotiTawar)
                                            .addComponent(MRotiGandum))
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(MRotiCoklat)
                                            .addComponent(MRotiKeju)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(MRotiIsi)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(MRotiPisang)))
                                .addGap(72, 72, 72)
                                .addComponent(jLabel8)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TPMeses)
                                    .addComponent(TPKeju)
                                    .addComponent(TPCoklat)
                                    .addComponent(TPKacang))))
                        .addContainerGap())))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Cash, Kembalian, TFTotal});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {TPCoklat, TPKacang, TPKeju, TPMeses});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {MRotiCoklat, MRotiGandum, MRotiIsi, MRotiKeju, MRotiPisang, MRotiTawar});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BKurangJumlah, BTambahJumlah});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel4, jLabel5, jLabel6, jLabel9});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFJumlahActionPerformed
        
    }//GEN-LAST:event_TFJumlahActionPerformed

    private void TambahPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahPesananActionPerformed
        if (!(menuPesanan == "" || menuPesanan == null)) {
            totalSemua += Integer.parseInt(TFTotal.getText().replace(",", ""));
            TFTotalSemua.setText(
                formatter.format((totalSemua > 100000) 
                    ? totalSemua - (totalSemua * 5 / 100) 
                    : totalSemua
                )
            );
            textPesanan += 
                menuPesanan + 
                toppingPesanan + 
                ", Jumlah: " + formatter.format(Integer.parseInt(TFJumlah.getText().replace(",", ""))) + 
                ", Total: " + formatter.format(Integer.parseInt(TFTotal.getText().replace(",", ""))) + "\n";
            Pesanan.setText(textPesanan);
            clear();
        }
    }//GEN-LAST:event_TambahPesananActionPerformed
    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        clear();
        totalSemua = 0;
        Pesanan.setText("");
        textPesanan = "";
        TFTotalSemua.setText("0");
        
        kurang.setText(" ");
        Cash.setText("0");
        Kembalian.setText("0");
    }//GEN-LAST:event_ResetActionPerformed
    private void clear() {
        BKurangJumlah.setEnabled(false);
        TFJumlah.setText("1");
        TFTotal.setText("0");
        
        menuPesanan = "";
        toppingPesanan = "";
        Menu.clearSelection();
        Topping.clearSelection();
        
        TPCoklat.setEnabled(false);
        TPKacang.setEnabled(false);
        TPKeju.setEnabled(false);
        TPMeses.setEnabled(false);
    }
    
    private void CashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CashKeyReleased
        hitungKembalian();
    }//GEN-LAST:event_CashKeyReleased

    private void TFJumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFJumlahKeyReleased
        try {
            String text = TFJumlah.getText().replace(",", "");
            if (text.isEmpty()) {
                BKurangJumlah.setEnabled(false);
            } else {
                int jumlah = Integer.parseInt(text);
                if (jumlah > 0) {
                    BKurangJumlah.setEnabled(jumlah > 1);
                    
                    TFJumlah.setText(Integer.toString(jumlah));
                    if (Integer.parseInt(TFTotal.getText().replace(",", "")) != 0) {
                        hitungTotal();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Input harus angka positif!", "Peringatan", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Input harus berupa angka!", "Peringatan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TFJumlahKeyReleased
    private void BKurangJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKurangJumlahActionPerformed
        try {
            int jumlah = TFJumlah.getText().isEmpty() ? 0 : Integer.parseInt(TFJumlah.getText().replace(",", ""));
            jumlah--;
            TFJumlah.setText(Integer.toString(jumlah));
            if (Integer.parseInt(TFTotal.getText().replace(",", "")) != 0) {
                hitungTotal();
            }
            if (jumlah <= 1 ) {
                BKurangJumlah.setEnabled(false);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "anda harus menginputkan angka", "peringatan", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_BKurangJumlahActionPerformed
    private void BTambahJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahJumlahActionPerformed
        try {
            int jumlah = TFJumlah.getText().isEmpty() ? 0 : Integer.parseInt(TFJumlah.getText().replace(",", ""));
            jumlah++;
            TFJumlah.setText(Integer.toString(jumlah));
            if (Integer.parseInt(TFTotal.getText().replace(",", "")) != 0) {
                hitungTotal();
            }
            if (jumlah > 1 ) {
                BKurangJumlah.setEnabled(true);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "anda harus menginputkan angka", "peringatan", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_BTambahJumlahActionPerformed

    private void TPKacangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPKacangActionPerformed
        hitungTotal();
    }//GEN-LAST:event_TPKacangActionPerformed
    private void TPCoklatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPCoklatActionPerformed
        hitungTotal();
    }//GEN-LAST:event_TPCoklatActionPerformed
    private void TPKejuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPKejuActionPerformed
        hitungTotal();
    }//GEN-LAST:event_TPKejuActionPerformed
    private void TPMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPMesesActionPerformed
        hitungTotal();
    }//GEN-LAST:event_TPMesesActionPerformed
    private void MRotiKejuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MRotiKejuActionPerformed
        hitungTotal();
    }//GEN-LAST:event_MRotiKejuActionPerformed
    private void MRotiGandumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MRotiGandumActionPerformed
        hitungTotal();
    }//GEN-LAST:event_MRotiGandumActionPerformed
    private void MRotiPisangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MRotiPisangActionPerformed
        hitungTotal();
    }//GEN-LAST:event_MRotiPisangActionPerformed
    private void MRotiIsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MRotiIsiActionPerformed
        hitungTotal();
    }//GEN-LAST:event_MRotiIsiActionPerformed
    private void MRotiCoklatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MRotiCoklatActionPerformed
        hitungTotal();
    }//GEN-LAST:event_MRotiCoklatActionPerformed
    private void MRotiTawarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MRotiTawarActionPerformed
        hitungTotal();
    }//GEN-LAST:event_MRotiTawarActionPerformed
    private void TFTotalSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTotalSemuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFTotalSemuaActionPerformed
    private void TFTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFTotalActionPerformed

    private void BeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeliActionPerformed
        if (menuPesanan != "" || totalSemua != 0 ) {
            int cash = 
                (Cash.getText().isEmpty())
                    ? 0 
                    : Integer.parseInt(Cash.getText().replace(",", "").replace(".", ""));
            if (cash < totalSemua) {
                JOptionPane.showMessageDialog(null, "Uang anda tidak cukup!", "Peringatan", JOptionPane.ERROR_MESSAGE);
                return;
            }
            int pilihan = JOptionPane.showConfirmDialog(null, "Anda yakin ingin membeli?", "peringatan", JOptionPane.YES_NO_OPTION);
            if (pilihan == JOptionPane.YES_OPTION) {
                clear();
                totalSemua = 0;
                Pesanan.setText("");
                textPesanan = "";
                TFTotalSemua.setText("0");

                kurang.setText(" ");
                Cash.setText("0");
                Kembalian.setText("0");
            }
        }
    }//GEN-LAST:event_BeliActionPerformed

    private void hitungTotal() {
        int menu;
        if (MRotiGandum.isSelected()) {
            menuPesanan = "Roti Gandum";
            menu = 17000;
        } else if (MRotiIsi.isSelected()) {
            menuPesanan = "Roti Isi";
            menu = 20000;
        } else if (MRotiCoklat.isSelected()) {
            menuPesanan = "Roti Coklat";
            menu = 18000;
        } else if (MRotiKeju.isSelected()) {
            menuPesanan = "Roti Keju";
            menu = 25000;
        } else if (MRotiPisang.isSelected()) {
            menuPesanan = "Roti Pisang";
            menu = 23000;
        } else if (MRotiTawar.isSelected()) {
            menuPesanan = "Roti Tawar";
            menu = 15000;
        } else {
            menuPesanan = "";
            menu = 0;
        }
        
        if (menu != 0) {
            TPCoklat.setEnabled(true);
            TPKacang.setEnabled(true);
            TPKeju.setEnabled(true);
            TPMeses.setEnabled(true);
        }
        
        int topping;
        if (TPCoklat.isSelected()) {
            toppingPesanan = " + Topping Coklat";
            topping = 5000;
        } else if (TPKeju.isSelected()) {
            toppingPesanan = " + Topping Keju";
            topping = 3000;
        } else if (TPKacang.isSelected()) {
            toppingPesanan = " + Topping Kacang";
            topping = 4000;
        } else if (TPMeses.isSelected()) {
            toppingPesanan = " + Topping Meses";
            topping = 4000;
        } else {
            toppingPesanan = "";
            topping = 0;
        }
        
        int jumlahPesanan = Integer.parseInt(TFJumlah.getText().replace(",", ""));
        int total = (menu + topping) * jumlahPesanan;
        TFTotal.setText(formatter.format(total));        
        
        if (totalSemua == 0) {
            TFTotalSemua.setText(
                formatter.format((total > 100000) 
                    ? total - (total * 5 / 100) 
                    : total
                )
            );
            Pesanan.setText(
                menuPesanan + 
                toppingPesanan + 
                ", Jumlah: " + formatter.format(Integer.parseInt(TFJumlah.getText().replace(",", ""))) + 
                ", Total: " + formatter.format(Integer.parseInt(TFTotal.getText().replace(",", "")))
            );
        } else {
            TFTotalSemua.setText(
                formatter.format(
                    ((totalSemua + total) > 100000) 
                        ? (totalSemua + total) - ((totalSemua + total) * 5 / 100) 
                        : (totalSemua + total)
                )
            );
            Pesanan.setText(
                textPesanan + 
                menuPesanan + 
                toppingPesanan + 
                ", Jumlah: " + formatter.format(Integer.parseInt(TFJumlah.getText().replace(",", ""))) + 
                ", Total: " + formatter.format(Integer.parseInt(TFTotal.getText().replace(",", "")))
            );
        }
        hitungKembalian();
    }
    
    private void hitungKembalian() {
        try {
            int cash = 
                (Cash.getText().isEmpty())
                    ? 0 
                    : Integer.parseInt(Cash.getText().replace(",", "").replace(".", ""));
            int total = Integer.parseInt(TFTotalSemua.getText().replace(",", ""));

            if(cash < total) {
                kurang.setText("Kurang " + formatter.format(Math.abs(cash-total)));
                Kembalian.setText("0");
            } else {
                kurang.setText(" ");
                Kembalian.setText(formatter.format(cash-total));
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Input harus berupa angka!", "Peringatan", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TokoRoti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TokoRoti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TokoRoti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TokoRoti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TokoRoti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BKurangJumlah;
    private javax.swing.JButton BTambahJumlah;
    private javax.swing.JButton Beli;
    private javax.swing.JTextField Cash;
    private javax.swing.JTextField Kembalian;
    private javax.swing.JRadioButton MRotiCoklat;
    private javax.swing.JRadioButton MRotiGandum;
    private javax.swing.JRadioButton MRotiIsi;
    private javax.swing.JRadioButton MRotiKeju;
    private javax.swing.JRadioButton MRotiPisang;
    private javax.swing.JRadioButton MRotiTawar;
    private javax.swing.ButtonGroup Menu;
    private javax.swing.JTextArea Pesanan;
    private javax.swing.JButton Reset;
    private javax.swing.JTextField TFJumlah;
    private javax.swing.JTextField TFTotal;
    private javax.swing.JTextField TFTotalSemua;
    private javax.swing.JRadioButton TPCoklat;
    private javax.swing.JRadioButton TPKacang;
    private javax.swing.JRadioButton TPKeju;
    private javax.swing.JRadioButton TPMeses;
    private javax.swing.JButton TambahPesanan;
    private javax.swing.ButtonGroup Topping;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kurang;
    // End of variables declaration//GEN-END:variables
}
