/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulir.pendaftaran;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class Tampilanformulir extends javax.swing.JFrame {

    public Tampilanformulir(String nama,String tempatlahir,String tanggallahir,String jeniskelamin, String alamat,String notelp,String email,String prodi, String fakultas){
        initComponents();
        Jtxtnama.setText(nama);
        Jtxttempatlahir.setText(tempatlahir);
        Jtxttanggallahir.setText(tanggallahir);
        Jtxtjeniskelamin.setText(jeniskelamin);
        Jtxtalamat.setText(alamat);
        Jtxtnotelp.setText(notelp);
        Jtxtemail.setText(email);
        Jtxtprodi.setText(prodi);
        Jtxtfakultas.setText(fakultas);
        setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JLnama = new javax.swing.JLabel();
        JLtempatlahir = new javax.swing.JLabel();
        JLtanggallahir = new javax.swing.JLabel();
        JLjeniskelamin = new javax.swing.JLabel();
        JLalamat = new javax.swing.JLabel();
        JLnotlp = new javax.swing.JLabel();
        JLemail = new javax.swing.JLabel();
        JLprodi = new javax.swing.JLabel();
        JLfakultas = new javax.swing.JLabel();
        Jtxtnama = new javax.swing.JTextField();
        Jtxttempatlahir = new javax.swing.JTextField();
        Jtxttanggallahir = new javax.swing.JTextField();
        Jtxtjeniskelamin = new javax.swing.JTextField();
        Jtxtalamat = new javax.swing.JTextField();
        Jtxtnotelp = new javax.swing.JTextField();
        Jtxtemail = new javax.swing.JTextField();
        Jtxtprodi = new javax.swing.JTextField();
        Jtxtfakultas = new javax.swing.JTextField();
        btnkeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulir/pendaftaran/logo_warga_lab-removebg-preview.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setText("UNIVERSITAS TRUNOJOYO MADURA");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Jl. Raya Telang PO. Box. 2 Kamal, Bangkalan-Madura");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Telp : (031) 3011146, Fax. (031) 3011506");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JLnama.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLnama.setForeground(new java.awt.Color(255, 255, 255));
        JLnama.setText("Nama :");

        JLtempatlahir.setBackground(new java.awt.Color(255, 255, 255));
        JLtempatlahir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLtempatlahir.setForeground(new java.awt.Color(255, 255, 255));
        JLtempatlahir.setText("Tempat Lahir :");

        JLtanggallahir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLtanggallahir.setForeground(new java.awt.Color(255, 255, 255));
        JLtanggallahir.setText("Tanggal Lahir :");

        JLjeniskelamin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLjeniskelamin.setForeground(new java.awt.Color(255, 255, 255));
        JLjeniskelamin.setText("Jenis Kelamin ;");

        JLalamat.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLalamat.setForeground(new java.awt.Color(255, 255, 255));
        JLalamat.setText("Alamat ;");

        JLnotlp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLnotlp.setForeground(new java.awt.Color(255, 255, 255));
        JLnotlp.setText("No. Telp. :");

        JLemail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLemail.setForeground(new java.awt.Color(255, 255, 255));
        JLemail.setText("Email ;");

        JLprodi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLprodi.setForeground(new java.awt.Color(255, 255, 255));
        JLprodi.setText("Prodi ;");

        JLfakultas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLfakultas.setForeground(new java.awt.Color(255, 255, 255));
        JLfakultas.setText("Fakultas ;");

        Jtxttanggallahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxttanggallahirActionPerformed(evt);
            }
        });

        Jtxtjeniskelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtjeniskelaminActionPerformed(evt);
            }
        });

        Jtxtnotelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtnotelpActionPerformed(evt);
            }
        });

        Jtxtprodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtprodiActionPerformed(evt);
            }
        });

        Jtxtfakultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtfakultasActionPerformed(evt);
            }
        });

        btnkeluar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnkeluar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLnama)
                            .addComponent(JLtempatlahir)
                            .addComponent(JLtanggallahir)
                            .addComponent(JLjeniskelamin)
                            .addComponent(JLalamat)
                            .addComponent(JLnotlp)
                            .addComponent(JLemail)
                            .addComponent(JLprodi)
                            .addComponent(JLfakultas))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Jtxtnama, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                            .addComponent(Jtxttempatlahir)
                            .addComponent(Jtxttanggallahir)
                            .addComponent(Jtxtjeniskelamin)
                            .addComponent(Jtxtalamat)
                            .addComponent(Jtxtnotelp)
                            .addComponent(Jtxtemail)
                            .addComponent(Jtxtfakultas)
                            .addComponent(Jtxtprodi))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLnama)
                    .addComponent(Jtxtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLtempatlahir)
                    .addComponent(Jtxttempatlahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLtanggallahir, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jtxttanggallahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLjeniskelamin)
                    .addComponent(Jtxtjeniskelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtxtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLalamat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLnotlp)
                    .addComponent(Jtxtnotelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLemail)
                    .addComponent(Jtxtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtxtprodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLprodi))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtxtfakultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLfakultas))
                .addGap(18, 18, 18)
                .addComponent(btnkeluar)
                .addGap(0, 64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
    btnkeluar.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        int confirmed = JOptionPane.showConfirmDialog(null, "Keluar Program?", "Keluar", JOptionPane.YES_NO_OPTION);
        if (confirmed == JOptionPane.YES_OPTION) {
            dispose();
        }
    }
});        // TODO add your handling code here:
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void JtxttanggallahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxttanggallahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxttanggallahirActionPerformed

    private void JtxtjeniskelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtjeniskelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtjeniskelaminActionPerformed

    private void JtxtnotelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtnotelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtnotelpActionPerformed

    private void JtxtprodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtprodiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtprodiActionPerformed

    private void JtxtfakultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtfakultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtfakultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tampilanformulir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tampilanformulir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tampilanformulir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tampilanformulir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLalamat;
    private javax.swing.JLabel JLemail;
    private javax.swing.JLabel JLfakultas;
    private javax.swing.JLabel JLjeniskelamin;
    private javax.swing.JLabel JLnama;
    private javax.swing.JLabel JLnotlp;
    private javax.swing.JLabel JLprodi;
    private javax.swing.JLabel JLtanggallahir;
    private javax.swing.JLabel JLtempatlahir;
    private javax.swing.JTextField Jtxtalamat;
    private javax.swing.JTextField Jtxtemail;
    private javax.swing.JTextField Jtxtfakultas;
    private javax.swing.JTextField Jtxtjeniskelamin;
    private javax.swing.JTextField Jtxtnama;
    private javax.swing.JTextField Jtxtnotelp;
    private javax.swing.JTextField Jtxtprodi;
    private javax.swing.JTextField Jtxttanggallahir;
    private javax.swing.JTextField Jtxttempatlahir;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
