/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package geebakery;

import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Bakery extends javax.swing.JFrame {
    
    private int jumlah = 0; 
    private int total = 0;  
    private int hargaTopping = 0; 
    private int hargaRoti = 0;
    
    
    /**
     * Creates new form Bakery
     */
    public Bakery() {
        initComponents();
        totalpricefield.setEditable(false);
        quantityfield.setEditable(false);
        changefield.setEditable(false);
        
        menugroup.add(rdbtnroquefort);
        menugroup.add(rdbtnroyalbloomer);
        menugroup.add(rdbtnsourdough);
        menugroup.add(rdbtnmiche);
        menugroup.add(rdbtngoldleaf);
        menugroup.add(rdbtnloaf);

        toppinggroup.add(rdbtnpistachio);
        toppinggroup.add(rdbtnalmond);
        toppinggroup.add(rdbtnglaze);
        toppinggroup.add(rdbtnparmesan);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menugroup = new javax.swing.ButtonGroup();
        toppinggroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rdbtnroquefort = new javax.swing.JRadioButton();
        rdbtnsourdough = new javax.swing.JRadioButton();
        rdbtngoldleaf = new javax.swing.JRadioButton();
        rdbtnroyalbloomer = new javax.swing.JRadioButton();
        rdbtnmiche = new javax.swing.JRadioButton();
        rdbtnloaf = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rdbtnpistachio = new javax.swing.JRadioButton();
        rdbtnalmond = new javax.swing.JRadioButton();
        rdbtnglaze = new javax.swing.JRadioButton();
        rdbtnparmesan = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        quantityfield = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btntotal = new javax.swing.JButton();
        totalpricefield = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        paymentfield = new javax.swing.JTextField();
        changefield = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("ARCO", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GEE BAKERY");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 40, 308, 48);

        jLabel2.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Comfort & Delicious");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 80, 180, 20);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Menu");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 160, 50, 21);

        menugroup.add(rdbtnroquefort);
        rdbtnroquefort.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        rdbtnroquefort.setForeground(new java.awt.Color(255, 255, 255));
        rdbtnroquefort.setText("Roquefort - Rp 100.000");
        rdbtnroquefort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnroquefortActionPerformed(evt);
            }
        });
        getContentPane().add(rdbtnroquefort);
        rdbtnroquefort.setBounds(10, 200, 190, 22);

        menugroup.add(rdbtnsourdough);
        rdbtnsourdough.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        rdbtnsourdough.setForeground(new java.awt.Color(255, 255, 255));
        rdbtnsourdough.setText("Sourdough - Rp 90.000");
        rdbtnsourdough.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnsourdoughActionPerformed(evt);
            }
        });
        getContentPane().add(rdbtnsourdough);
        rdbtnsourdough.setBounds(230, 200, 190, 22);

        menugroup.add(rdbtngoldleaf);
        rdbtngoldleaf.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        rdbtngoldleaf.setForeground(new java.awt.Color(255, 255, 255));
        rdbtngoldleaf.setText("Gold Leaf - Rp 150.000");
        rdbtngoldleaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtngoldleafActionPerformed(evt);
            }
        });
        getContentPane().add(rdbtngoldleaf);
        rdbtngoldleaf.setBounds(410, 200, 160, 21);

        menugroup.add(rdbtnroyalbloomer);
        rdbtnroyalbloomer.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        rdbtnroyalbloomer.setForeground(new java.awt.Color(255, 255, 255));
        rdbtnroyalbloomer.setText("Royal Bloomer - Rp 160.000");
        rdbtnroyalbloomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnroyalbloomerActionPerformed(evt);
            }
        });
        getContentPane().add(rdbtnroyalbloomer);
        rdbtnroyalbloomer.setBounds(10, 250, 190, 22);

        menugroup.add(rdbtnmiche);
        rdbtnmiche.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        rdbtnmiche.setForeground(new java.awt.Color(255, 255, 255));
        rdbtnmiche.setText("Miche - Rp 70.000");
        rdbtnmiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnmicheActionPerformed(evt);
            }
        });
        getContentPane().add(rdbtnmiche);
        rdbtnmiche.setBounds(230, 250, 150, 22);

        menugroup.add(rdbtnloaf);
        rdbtnloaf.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        rdbtnloaf.setForeground(new java.awt.Color(255, 255, 255));
        rdbtnloaf.setText("Shepherd Loaf - Rp 100.000");
        rdbtnloaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnloafActionPerformed(evt);
            }
        });
        getContentPane().add(rdbtnloaf);
        rdbtnloaf.setBounds(410, 250, 200, 21);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Topping");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(260, 320, 70, 21);

        toppinggroup.add(rdbtnpistachio);
        rdbtnpistachio.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        rdbtnpistachio.setForeground(new java.awt.Color(255, 255, 255));
        rdbtnpistachio.setText("Pistachio - Rp 25.000");
        rdbtnpistachio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnpistachioActionPerformed(evt);
            }
        });
        getContentPane().add(rdbtnpistachio);
        rdbtnpistachio.setBounds(20, 360, 150, 22);

        toppinggroup.add(rdbtnalmond);
        rdbtnalmond.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        rdbtnalmond.setForeground(new java.awt.Color(255, 255, 255));
        rdbtnalmond.setText("Almond - Rp 20.000");
        rdbtnalmond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnalmondActionPerformed(evt);
            }
        });
        getContentPane().add(rdbtnalmond);
        rdbtnalmond.setBounds(170, 360, 150, 22);

        toppinggroup.add(rdbtnglaze);
        rdbtnglaze.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        rdbtnglaze.setForeground(new java.awt.Color(255, 255, 255));
        rdbtnglaze.setText("Glaze - Rp 30.000");
        rdbtnglaze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnglazeActionPerformed(evt);
            }
        });
        getContentPane().add(rdbtnglaze);
        rdbtnglaze.setBounds(310, 360, 130, 22);

        toppinggroup.add(rdbtnparmesan);
        rdbtnparmesan.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        rdbtnparmesan.setForeground(new java.awt.Color(255, 255, 255));
        rdbtnparmesan.setText("Parmesan - Rp 20.000");
        rdbtnparmesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnparmesanActionPerformed(evt);
            }
        });
        getContentPane().add(rdbtnparmesan);
        rdbtnparmesan.setBounds(440, 360, 160, 22);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 410, 790, 16);

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pembayaran");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(240, 430, 110, 21);

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jumlah :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(190, 460, 50, 15);
        getContentPane().add(quantityfield);
        quantityfield.setBounds(190, 480, 90, 22);

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 510, 40, 30);

        jButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton2.setText("-");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 510, 40, 30);

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(320, 460, 35, 15);

        btntotal.setText("Total");
        btntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotalActionPerformed(evt);
            }
        });
        getContentPane().add(btntotal);
        btntotal.setBounds(320, 480, 60, 23);

        totalpricefield.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        getContentPane().add(totalpricefield);
        totalpricefield.setBounds(380, 480, 71, 24);

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cash :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(190, 550, 40, 15);

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Kembali :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(320, 550, 60, 15);

        paymentfield.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        paymentfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentfieldActionPerformed(evt);
            }
        });
        getContentPane().add(paymentfield);
        paymentfield.setBounds(190, 570, 90, 24);

        changefield.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        getContentPane().add(changefield);
        changefield.setBounds(320, 570, 100, 24);

        jButton4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jButton4.setText("Konfirmasi Pesanan");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(240, 630, 150, 20);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lovepik-baking-bread-png-image_401464462_wh860-removebg-preview.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(450, 580, 150, 90);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngtree-pastry-bakery-png-image_13863315-removebg-preview.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 430, 150, 120);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Мятая бумага черного цвета - фон для оформления блога.jpeg"))); // NOI18N
        jLabel14.setText("-");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 130, 600, 550);

        jButton3.setBackground(new java.awt.Color(51, 204, 0));
        jButton3.setText("Reset");
        getContentPane().add(jButton3);
        jButton3.setBounds(140, 630, 72, 23);

        jButton5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jButton5.setText("Batalkan Pesanan");
        getContentPane().add(jButton5);
        jButton5.setBounds(230, 630, 140, 20);

        jButton6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jButton6.setText("Batalkan Pesanan");
        getContentPane().add(jButton6);
        jButton6.setBounds(240, 630, 140, 20);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot_2024-10-09_092241-removebg-preview.png"))); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(110, 30, 90, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download (2).jpeg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-3, -4, 610, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbtnloafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnloafActionPerformed
        // TODO add your handling code here:
        hargaRoti = 100000;
    }//GEN-LAST:event_rdbtnloafActionPerformed

    private void paymentfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentfieldActionPerformed

    private void btntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotalActionPerformed
        // TODO add your handling code here:
        if (hargaRoti == 0){
            JOptionPane.showMessageDialog(this, "pilih salah satu jenis roti terlebih dahulu", "error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        

    
        
        total = jumlah * (hargaRoti + hargaTopping);
        if (total > 100000) {
        double diskon = total * 0.05; 
        total -= diskon; 
        
        ImageIcon icon = new ImageIcon("C:/Users/Lenovo/Downloads/discount.png");
        
        JOptionPane.showMessageDialog(this, "Anda mendapatkan diskon 5%!", "Diskon", JOptionPane.INFORMATION_MESSAGE,icon);
        }
        totalpricefield.setText(String.valueOf(total));
        
        String cashInput = paymentfield.getText();
    if (cashInput.isEmpty() || !cashInput.matches("\\d+")) {
        
    }
        int uangDibayarkan = Integer.parseInt(paymentfield.getText()); 
        int kembalian = uangDibayarkan - total; 
        
        if (kembalian < 0 ){
            JOptionPane.showMessageDialog(this, "uang tidak mencukupi ", "error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        changefield.setText(String.valueOf(kembalian));
        
            
            
    }//GEN-LAST:event_btntotalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jumlah++; 
        quantityfield.setText(String.valueOf(jumlah));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jumlah > 0 ){
            jumlah--; 
            quantityfield.setText(String.valueOf(jumlah));
        }else{
            JOptionPane.showMessageDialog(this, "pesanan tidak boleh kurang dari 0", "error", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jumlah = 0 ; 
        total = 0 ; 
        hargaTopping = 0 ; 
        hargaRoti = 0 ; 
        
        quantityfield.setText("");
        totalpricefield.setText("");
        paymentfield.setText("");
        changefield.setText("");
        toppinggroup.clearSelection(); 
        menugroup.clearSelection(); 
        repaint();
        revalidate();
        
        JOptionPane.showConfirmDialog(null, "Terima Kasih Sudah Memesan", "confirm", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void rdbtnroquefortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnroquefortActionPerformed
        // TODO add your handling code here:
        hargaRoti = 100000;
    }//GEN-LAST:event_rdbtnroquefortActionPerformed

    private void rdbtnroyalbloomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnroyalbloomerActionPerformed
        // TODO add your handling code here:
        hargaRoti = 160000;
    }//GEN-LAST:event_rdbtnroyalbloomerActionPerformed

    private void rdbtnsourdoughActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnsourdoughActionPerformed
        // TODO add your handling code here:
        hargaRoti = 90000;
    }//GEN-LAST:event_rdbtnsourdoughActionPerformed

    private void rdbtnmicheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnmicheActionPerformed
        // TODO add your handling code here:
        hargaRoti = 70000;
    }//GEN-LAST:event_rdbtnmicheActionPerformed

    private void rdbtngoldleafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtngoldleafActionPerformed
        // TODO add your handling code here:
        hargaRoti = 150000;
    }//GEN-LAST:event_rdbtngoldleafActionPerformed

    private void rdbtnpistachioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnpistachioActionPerformed
        // TODO add your handling code here:
        hargaTopping = 25000;
    }//GEN-LAST:event_rdbtnpistachioActionPerformed

    private void rdbtnalmondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnalmondActionPerformed
        // TODO add your handling code here:
        hargaTopping = 20000;
    }//GEN-LAST:event_rdbtnalmondActionPerformed

    private void rdbtnglazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnglazeActionPerformed
        // TODO add your handling code here:
        hargaTopping = 30000;
    }//GEN-LAST:event_rdbtnglazeActionPerformed

    private void rdbtnparmesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnparmesanActionPerformed
        // TODO add your handling code here:
        hargaTopping = 20000;
    }//GEN-LAST:event_rdbtnparmesanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bakery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bakery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bakery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bakery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bakery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntotal;
    private javax.swing.JTextField changefield;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.ButtonGroup menugroup;
    private javax.swing.JTextField paymentfield;
    private javax.swing.JTextField quantityfield;
    private javax.swing.JRadioButton rdbtnalmond;
    private javax.swing.JRadioButton rdbtnglaze;
    private javax.swing.JRadioButton rdbtngoldleaf;
    private javax.swing.JRadioButton rdbtnloaf;
    private javax.swing.JRadioButton rdbtnmiche;
    private javax.swing.JRadioButton rdbtnparmesan;
    private javax.swing.JRadioButton rdbtnpistachio;
    private javax.swing.JRadioButton rdbtnroquefort;
    private javax.swing.JRadioButton rdbtnroyalbloomer;
    private javax.swing.JRadioButton rdbtnsourdough;
    private javax.swing.ButtonGroup toppinggroup;
    private javax.swing.JTextField totalpricefield;
    // End of variables declaration//GEN-END:variables
}
