/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas1;

/**
 *
 * @author HP
 */
public class TokoApotek extends javax.swing.JFrame {

    /**
     * Creates new form TokoApotek
     */
    public TokoApotek() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MediChoice = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Paracetamol = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Bodrex = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Entrostop = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Mixagrip = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Mylanta = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Combi = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Paramex = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Promag = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Sangobion = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Komix = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Combantrin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas1/img/LOGO KIMIA FARMA New.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(330, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(304, 304, 304))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(214, 214, 214));
        jPanel2.setMaximumSize(new java.awt.Dimension(700, 520));
        jPanel2.setMinimumSize(new java.awt.Dimension(400, 175));
        jPanel2.setPreferredSize(new java.awt.Dimension(7000, 520));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 15));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(170, 150));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas1/img/MediChoiceNew.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 66));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        jPanel3.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("MEDI CHOICE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 21, 0, 14);
        jPanel3.add(jLabel2, gridBagConstraints);

        MediChoice.setBackground(new java.awt.Color(51, 204, 0));
        MediChoice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MediChoice.setForeground(new java.awt.Color(255, 255, 255));
        MediChoice.setText("DETAIL");
        MediChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MediChoiceActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel3.add(MediChoice, gridBagConstraints);

        jPanel2.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(170, 150));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas1/img/paracetamolNew.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 66));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        jPanel4.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("PARACETAMOL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 21, 0, 14);
        jPanel4.add(jLabel4, gridBagConstraints);

        Paracetamol.setBackground(new java.awt.Color(51, 204, 0));
        Paracetamol.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Paracetamol.setForeground(new java.awt.Color(255, 255, 255));
        Paracetamol.setText("DETAIL");
        Paracetamol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParacetamolActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel4.add(Paracetamol, gridBagConstraints);

        jPanel2.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(170, 150));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas1/img/bodrexNew.png"))); // NOI18N
        jLabel5.setText("jLabel1");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 66));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 8);
        jPanel5.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("BODREX");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 21, 0, 22);
        jPanel5.add(jLabel6, gridBagConstraints);

        Bodrex.setBackground(new java.awt.Color(51, 204, 0));
        Bodrex.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bodrex.setForeground(new java.awt.Color(255, 255, 255));
        Bodrex.setText("DETAIL");
        Bodrex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BodrexActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 13);
        jPanel5.add(Bodrex, gridBagConstraints);

        jPanel2.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(170, 150));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas1/img/entrostopNew.png"))); // NOI18N
        jLabel7.setText("jLabel1");
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 66));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        jPanel6.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("ENTROSTOP");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 21, 0, 14);
        jPanel6.add(jLabel8, gridBagConstraints);

        Entrostop.setBackground(new java.awt.Color(51, 204, 0));
        Entrostop.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Entrostop.setForeground(new java.awt.Color(255, 255, 255));
        Entrostop.setText("DETAIL");
        Entrostop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrostopActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel6.add(Entrostop, gridBagConstraints);

        jPanel2.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(170, 150));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas1/img/mixagripNew.png"))); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(100, 66));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        jPanel7.add(jLabel11, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("MIXAGRIP FLU & BATUK");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 21, 0, 14);
        jPanel7.add(jLabel12, gridBagConstraints);

        Mixagrip.setBackground(new java.awt.Color(51, 204, 0));
        Mixagrip.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Mixagrip.setForeground(new java.awt.Color(255, 255, 255));
        Mixagrip.setText("DETAIL");
        Mixagrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MixagripActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel7.add(Mixagrip, gridBagConstraints);

        jPanel2.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(170, 150));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas1/img/mylantaNew.png"))); // NOI18N
        jLabel9.setText("jLabel1");
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 66));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        jPanel8.add(jLabel9, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("MYLANTA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 21, 0, 14);
        jPanel8.add(jLabel10, gridBagConstraints);

        Mylanta.setBackground(new java.awt.Color(51, 204, 0));
        Mylanta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Mylanta.setForeground(new java.awt.Color(255, 255, 255));
        Mylanta.setText("DETAIL");
        Mylanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MylantaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPanel8.add(Mylanta, gridBagConstraints);

        jPanel2.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(170, 150));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas1/img/OBHNew.png"))); // NOI18N
        jLabel13.setText("jLabel1");
        jLabel13.setPreferredSize(new java.awt.Dimension(100, 66));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        jPanel9.add(jLabel13, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("OBH COMBI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 21, 0, 14);
        jPanel9.add(jLabel14, gridBagConstraints);

        Combi.setBackground(new java.awt.Color(51, 204, 0));
        Combi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Combi.setForeground(new java.awt.Color(255, 255, 255));
        Combi.setText("DETAIL");
        Combi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel9.add(Combi, gridBagConstraints);

        jPanel2.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(170, 150));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas1/img/paramexNew.png"))); // NOI18N
        jLabel15.setText("jLabel1");
        jLabel15.setPreferredSize(new java.awt.Dimension(100, 66));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        jPanel10.add(jLabel15, gridBagConstraints);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("PARAMEX");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 21, 0, 14);
        jPanel10.add(jLabel16, gridBagConstraints);

        Paramex.setBackground(new java.awt.Color(51, 204, 0));
        Paramex.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Paramex.setForeground(new java.awt.Color(255, 255, 255));
        Paramex.setText("DETAIL");
        Paramex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParamexActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPanel10.add(Paramex, gridBagConstraints);

        jPanel2.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(170, 150));
        jPanel11.setLayout(new java.awt.GridBagLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas1/img/PromagNew.png"))); // NOI18N
        jLabel17.setText("jLabel1");
        jLabel17.setPreferredSize(new java.awt.Dimension(100, 66));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        jPanel11.add(jLabel17, gridBagConstraints);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setText("PROMAG");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 21, 0, 14);
        jPanel11.add(jLabel18, gridBagConstraints);

        Promag.setBackground(new java.awt.Color(51, 204, 0));
        Promag.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Promag.setForeground(new java.awt.Color(255, 255, 255));
        Promag.setText("DETAIL");
        Promag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromagActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        jPanel11.add(Promag, gridBagConstraints);

        jPanel2.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setPreferredSize(new java.awt.Dimension(170, 150));
        jPanel12.setLayout(new java.awt.GridBagLayout());

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas1/img/sangobionNew.png"))); // NOI18N
        jLabel21.setText("jLabel1");
        jLabel21.setPreferredSize(new java.awt.Dimension(100, 66));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        jPanel12.add(jLabel21, gridBagConstraints);

        jLabel22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel22.setText("SANGOBION");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 21, 0, 14);
        jPanel12.add(jLabel22, gridBagConstraints);

        Sangobion.setBackground(new java.awt.Color(51, 204, 0));
        Sangobion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Sangobion.setForeground(new java.awt.Color(255, 255, 255));
        Sangobion.setText("DETAIL");
        Sangobion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SangobionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel12.add(Sangobion, gridBagConstraints);

        jPanel2.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setPreferredSize(new java.awt.Dimension(170, 150));
        jPanel13.setLayout(new java.awt.GridBagLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas1/img/KomixHerbalNew.png"))); // NOI18N
        jLabel19.setText("jLabel1");
        jLabel19.setPreferredSize(new java.awt.Dimension(100, 66));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        jPanel13.add(jLabel19, gridBagConstraints);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel20.setText("KOMIX HERBAL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 21, 0, 14);
        jPanel13.add(jLabel20, gridBagConstraints);

        Komix.setBackground(new java.awt.Color(51, 204, 0));
        Komix.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Komix.setForeground(new java.awt.Color(255, 255, 255));
        Komix.setText("DETAIL");
        Komix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KomixActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel13.add(Komix, gridBagConstraints);

        jPanel2.add(jPanel13);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setPreferredSize(new java.awt.Dimension(170, 150));
        jPanel14.setLayout(new java.awt.GridBagLayout());

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas1/img/combantrinNew.png"))); // NOI18N
        jLabel23.setText("jLabel1");
        jLabel23.setPreferredSize(new java.awt.Dimension(100, 66));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPanel14.add(jLabel23, gridBagConstraints);

        jLabel24.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel24.setText("COMBANTRIN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 21, 0, 14);
        jPanel14.add(jLabel24, gridBagConstraints);

        Combantrin.setBackground(new java.awt.Color(51, 204, 0));
        Combantrin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Combantrin.setForeground(new java.awt.Color(255, 255, 255));
        Combantrin.setText("DETAIL");
        Combantrin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombantrinActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel14.add(Combantrin, gridBagConstraints);

        jPanel2.add(jPanel14);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BodrexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BodrexActionPerformed
        String deskripsi = 
            "Nama Obat :\n"
            + "Bodrex FLU & BATUK\n"
            + "Dosis :\n"
            + " - Dewasa : 1 kaplet 3x sehari\n"
            + " - Anak Anak : -\n"
            + "\n"
            + "Indikasi umum :"
            + "meredakan gejala flu"
            + "meredakan gejala batuk"
            + "meredakan gejala sakit kepala"
            + "meredakan gejala demam" 
        ;
        detail d = new detail();
        d.ubah("bodrexDetail.png", deskripsi);
        d.setVisible(true);
    }//GEN-LAST:event_BodrexActionPerformed
    private void CombantrinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombantrinActionPerformed
        String deskripsi = 
            "Nama Obat :\n"
            + "Combantrin\n"
            + "Dosis :\n"
            + " - anak 2-6 tahun : 5-10 ml\n"
            + " - anak 6-12 tahun : 10-15 ml\n"
            + " - anak > 12 tahun : 20 ml\n"
            + "\n"
            + "Indikasi umum :"
            + "Digunakan untuk mengobati infeksi cacing kremi, cacing galang, cacing tambang"
        ;
        detail d = new detail();
        d.ubah("combantrinDetail.png", deskripsi);
        d.setVisible(true);
    }//GEN-LAST:event_CombantrinActionPerformed
    private void ParacetamolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParacetamolActionPerformed
        String deskripsi = 
            "Nama Obat :\n"
            + "Paracetamol\n"
            + "Dosis :\n"
            + " - anak 6-12 tahun : 2x sehari\n"
            + " - anak > 12 tahun : 3x sehari\n"
            + "\n"
            + "Indikasi umum :"
            + "meredakan nyeri ringan hingga seperti sakit kepala, sakit gigi, nyeri otot, serta menurunkan demam"
        ;
        detail d = new detail();
        d.ubah("paracetamolDetail.png", deskripsi);
        d.setVisible(true);
    }//GEN-LAST:event_ParacetamolActionPerformed
    private void EntrostopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrostopActionPerformed
        String deskripsi = 
            "Nama Obat :\n"
            + "Entrostop\n"
            + "Dosis :\n"
            + " - anak 6-12 tahun : 1x setelah setiap diare\n"
            + " - anak > 12 tahun : 2x setelah setiap diare\n"
            + "\n"
            + "Indikasi umum :"
            + "untuk mengatasi diare yang tidak diketahui penyebabnya dengan jelas"
        ;
        detail d = new detail();
        d.ubah("entrostopDetail.png", deskripsi);
        d.setVisible(true);
    }//GEN-LAST:event_EntrostopActionPerformed
    private void MediChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MediChoiceActionPerformed
        String deskripsi = 
            "Nama Obat :\n"
            + "Medi Choice\n"
            + "Dosis :\n"
            + " - anak 6-12 tahun : 2x sehari\n"
            + " - anak > 12 tahun : 3x sehari\n"
            + "\n"
            + "Indikasi umum :"
            + "meredakan nyeri ringan hingga seperti sakit kepala, sakit gigi, nyeri otot, serta menurunkan demam"
        ;
        detail d = new detail();
        d.ubah("MediChoiceDetail.png", deskripsi);
        d.setVisible(true);
    }//GEN-LAST:event_MediChoiceActionPerformed
    private void MixagripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MixagripActionPerformed
        String deskripsi = 
            "Nama Obat :\n"
            + "Mixagrip\n"
            + "Dosis :\n"
            + " - anak 6-12 tahun : 2x sehari\n"
            + " - anak > 12 tahun : 3x sehari\n"
            + "\n"
            + "Indikasi umum :"
            + "meredakan gejala flu yang disertai batuk"
        ;
        detail d = new detail();
        d.ubah("mixagripDetail.png", deskripsi);
        d.setVisible(true);
    }//GEN-LAST:event_MixagripActionPerformed
    private void MylantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MylantaActionPerformed
        String deskripsi = 
            "Nama Obat :\n"
            + "Mylanta\n"
            + "Dosis :\n"
            + " - anak 6-12 tahun : 1-2x sendok 3-4x sehari\n"
            + " - anak > 12 tahun : 1/2-1x sendok 3-4x sehari\n"
            + "\n"
            + "Indikasi umum :"
            + "meredakan gejala mual"
            + "meredakan gejala nyeri lambung"
            + "meredakan gejala gejal yang berhubungan dengan asam lambung"
        ;
        detail d = new detail();
        d.ubah("mylantaDetail.png", deskripsi);
        d.setVisible(true);
    }//GEN-LAST:event_MylantaActionPerformed
    private void CombiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombiActionPerformed
        String deskripsi = 
            "Nama Obat :\n"
            + "OBH Combi\n"
            + "Dosis :\n"
            + " - Dewasa > 12 tahun : 1 sachet 3x sehari\n"
            + "\n"
            + "Indikasi umum :"
            + "Meredakan batuk yang disertai gejala flu, demam, bersin dan hidung tersumbat"
        ;
        detail d = new detail();
        d.ubah("OBHDetail.png", deskripsi);
        d.setVisible(true);
    }//GEN-LAST:event_CombiActionPerformed
    private void PromagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromagActionPerformed
        String deskripsi = 
            "Nama Obat :\n"
            + "Promag\n"
            + "Dosis :\n"
            + " - anak 6-12 tahun : 1-2x sendok 3-4x sehari\n"
            + " - anak > 12 tahun : 1/2-1x sendok 3-4x sehari\n"
            + "\n"
            + "Indikasi umum :"
            + "meredakan gejala mual"
            + "meredakan gejala nyeri lambung"
            + "meredakan gejala gejal yang berhubungan dengan asam lambung"
        ;
        detail d = new detail();
        d.ubah("PromagDetail.png", deskripsi);
        d.setVisible(true);
    }//GEN-LAST:event_PromagActionPerformed
    private void ParamexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParamexActionPerformed
        String deskripsi = 
            "Nama Obat :\n"
            + "Paramex\n"
            + "Dosis :\n"
            + " - Dewasa : 1 kaplet 2-3x sehari\n"
            + " - Anak Anak : -\n"
            + "\n"
            + "Indikasi umum :"
            + "meredakan gejala flu"
            + "meredakan gejala sakit kepala"
            + "meredakan gejala demam" 
        ;
        detail d = new detail();
        d.ubah("paramexDetail.png", deskripsi);
        d.setVisible(true);
    }//GEN-LAST:event_ParamexActionPerformed
    private void SangobionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SangobionActionPerformed
        String deskripsi = 
            "Nama Obat :\n"
            + "Sangobion\n"
            + "Dosis :\n"
            + " - Dewasa : 1 kapsul 1x sehari\n"
            + " - Anak Anak : -\n"
            + "\n"
            + "Indikasi umum :"
            + "untuk anemia kekurangan zat besi dan mineral lain yang membantu pembuatan darah"
        ;
        detail d = new detail();
        d.ubah("sangobionDetail.png", deskripsi);
        d.setVisible(true);
    }//GEN-LAST:event_SangobionActionPerformed
    private void KomixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KomixActionPerformed
        String deskripsi = 
            "Nama Obat :\n"
            + "Komix\n"
            + "Dosis :\n"
            + " - Dewasa > 12 tahun : 1 sachet 3x sehari\n"
            + "\n"
            + "Indikasi umum :"
            + "Meredakan batuk yang disertai gejala flu, demam, bersin dan hidung tersumbat"
        ;
        detail d = new detail();
        d.ubah("KomixHerbalDetail.png", deskripsi);
        d.setVisible(true);
    }//GEN-LAST:event_KomixActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TokoApotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TokoApotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TokoApotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TokoApotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TokoApotek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bodrex;
    private javax.swing.JButton Combantrin;
    private javax.swing.JButton Combi;
    private javax.swing.JButton Entrostop;
    private javax.swing.JButton Komix;
    private javax.swing.JButton MediChoice;
    private javax.swing.JButton Mixagrip;
    private javax.swing.JButton Mylanta;
    private javax.swing.JButton Paracetamol;
    private javax.swing.JButton Paramex;
    private javax.swing.JButton Promag;
    private javax.swing.JButton Sangobion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
