/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul2;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class TokoRoti extends javax.swing.JFrame {

    double hargaKue,hargaTopping;
    int jumlahPesanan;
    
    public TokoRoti() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        KueCokelatLumer = new javax.swing.JRadioButton();
        Cheesake = new javax.swing.JRadioButton();
        Tiramisu = new javax.swing.JRadioButton();
        RedVelvetCake = new javax.swing.JRadioButton();
        BrownisKukus = new javax.swing.JRadioButton();
        PuddingBuah = new javax.swing.JRadioButton();
        KueLapisLegit = new javax.swing.JRadioButton();
        BlackForest = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        KejuParut = new javax.swing.JRadioButton();
        KacangAlmond = new javax.swing.JRadioButton();
        BuahCeri = new javax.swing.JRadioButton();
        CokelatChips = new javax.swing.JRadioButton();
        NoTopping = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        Tambah = new javax.swing.JButton();
        JumlahPesanan = new javax.swing.JTextField();
        Kurang = new javax.swing.JButton();
        Hitung = new javax.swing.JButton();
        Total = new javax.swing.JTextField();
        Kembalian = new javax.swing.JTextField();
        Cash = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Reset = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\LOGO_RB-removebg-preview-removebg-preview.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        jLabel2.setText("RENDY BAKERY");

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel3.setText("Dsn.gempolnogo Ds.gempolmanis");

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel4.setText("Kec.Sambeng Kab.Lamongan Prov.JawaTimur");

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jLabel5.setBackground(new java.awt.Color(51, 102, 0));
        jLabel5.setFont(new java.awt.Font("Felix Titling", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("MENU :");

        buttonGroup1.add(KueCokelatLumer);
        KueCokelatLumer.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        KueCokelatLumer.setText("Kue Cokelat lumer- Rp.25.000");

        buttonGroup1.add(Cheesake);
        Cheesake.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Cheesake.setText("Cheesake- Rp.30.000");

        buttonGroup1.add(Tiramisu);
        Tiramisu.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Tiramisu.setText("Tiramisu- Rp.35.000");

        buttonGroup1.add(RedVelvetCake);
        RedVelvetCake.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        RedVelvetCake.setText("Red velvet Cake- Rp.28.000");

        buttonGroup1.add(BrownisKukus);
        BrownisKukus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BrownisKukus.setText("Brownis Kukus- Rp.22.000");

        buttonGroup1.add(PuddingBuah);
        PuddingBuah.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PuddingBuah.setText("Pudding Buah- Rp.18.000");

        buttonGroup1.add(KueLapisLegit);
        KueLapisLegit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        KueLapisLegit.setText("Kue Lapis Legit- Rp.40.000 ");

        buttonGroup1.add(BlackForest);
        BlackForest.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BlackForest.setText("Black Forest- Rp.32.000");
        BlackForest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlackForestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KueCokelatLumer)
                            .addComponent(PuddingBuah)
                            .addComponent(RedVelvetCake)
                            .addComponent(BrownisKukus))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BlackForest)
                                .addComponent(KueLapisLegit))
                            .addComponent(Cheesake, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tiramisu, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel5)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KueLapisLegit)
                    .addComponent(KueCokelatLumer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(RedVelvetCake)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PuddingBuah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BrownisKukus))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BlackForest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Tiramisu)
                        .addGap(12, 12, 12)
                        .addComponent(Cheesake)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 153));

        jLabel6.setFont(new java.awt.Font("Felix Titling", 0, 14)); // NOI18N
        jLabel6.setText("TOPING :");

        buttonGroup2.add(KejuParut);
        KejuParut.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        KejuParut.setText("Keju Parut- Rp.6.000");

        buttonGroup2.add(KacangAlmond);
        KacangAlmond.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        KacangAlmond.setText("Kacang Almond- Rp.7.000");

        buttonGroup2.add(BuahCeri);
        BuahCeri.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BuahCeri.setText("Buah Ceri- Rp.5.000");

        buttonGroup2.add(CokelatChips);
        CokelatChips.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CokelatChips.setText("Cokelat Chips- Rp.6.000");

        NoTopping.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NoTopping.setText("No Topping- Rp.0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KacangAlmond)
                            .addComponent(KejuParut)
                            .addComponent(BuahCeri)
                            .addComponent(CokelatChips)
                            .addComponent(NoTopping)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel6)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(KejuParut)
                .addGap(12, 12, 12)
                .addComponent(KacangAlmond)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BuahCeri)
                .addGap(12, 12, 12)
                .addComponent(CokelatChips)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NoTopping)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Tambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Tambah.setText("+");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });

        JumlahPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahPesananActionPerformed(evt);
            }
        });

        Kurang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Kurang.setText("-");
        Kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KurangActionPerformed(evt);
            }
        });

        Hitung.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Hitung.setForeground(new java.awt.Color(0, 153, 153));
        Hitung.setText("HITUNG");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        jLabel7.setText("Jumlah :");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("PEMBAYARAN");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Cash :");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Kembalian :");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("TOTAL :");

        Reset.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Reset.setForeground(new java.awt.Color(204, 0, 0));
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Keluar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Keluar.setForeground(new java.awt.Color(51, 0, 255));
        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Reset)
                                .addGap(18, 18, 18)
                                .addComponent(Keluar))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Kurang, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JumlahPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel7)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(185, 185, 185))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Kembalian, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(Cash)
                                    .addComponent(Total))
                                .addGap(96, 96, 96))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Hitung)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Kurang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JumlahPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hitung)
                    .addComponent(Reset)
                    .addComponent(Keluar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BlackForestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlackForestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BlackForestActionPerformed

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        // TODO add your handling code here:
        jumlahPesanan++;
        JumlahPesanan.setText(String.valueOf(jumlahPesanan));
    }//GEN-LAST:event_TambahActionPerformed

    private void JumlahPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahPesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahPesananActionPerformed

    private void KurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KurangActionPerformed
        // TODO add your handling code here:
         if (jumlahPesanan > 0){
            jumlahPesanan--;
            JumlahPesanan.setText(String.valueOf(jumlahPesanan));
        }
    }//GEN-LAST:event_KurangActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
         if (!KueCokelatLumer.isSelected() && !RedVelvetCake.isSelected() && !PuddingBuah.isSelected() && !BrownisKukus.isSelected() && !KueLapisLegit.isSelected() && !BlackForest.isSelected() &&
        !Tiramisu.isSelected() && !Cheesake.isSelected()) {
        JOptionPane.showMessageDialog(this, "Silakan pilih jenis Kue terlebih dahulu!");
        return;
        }
        
        if (!KejuParut.isSelected() && !KacangAlmond.isSelected() && !BuahCeri.isSelected() && !CokelatChips.isSelected() && !NoTopping.isSelected()) {
        JOptionPane.showMessageDialog(this, "Silakan pilih topping terlebih dahulu!");
        return;
        }
        
        if(KueCokelatLumer.isSelected()){
            hargaKue = 25000;
        }else if(RedVelvetCake.isSelected()){
            hargaKue = 28000;
        }else if(PuddingBuah.isSelected()){
            hargaKue = 18000;
        }else if(BrownisKukus.isSelected()){
            hargaKue = 22000;
        }else if(BlackForest.isSelected()){
            hargaKue = 32000;
        }else if(Tiramisu.isSelected()){
            hargaKue = 35000;
        }else if(Cheesake.isSelected()){
            hargaKue = 35000;
        }
        
        if(KejuParut.isSelected()){
            hargaTopping = 6000;
        }else if(KacangAlmond.isSelected()){
            hargaTopping = 7000;
        }else if(BuahCeri.isSelected()){
            hargaTopping = 5000;
        }else if(CokelatChips.isSelected()){
            hargaTopping = 6000;
        }else if(NoTopping.isSelected()){
            hargaTopping = 0;
        }
        
        double totalHarga = (hargaKue + hargaTopping)*jumlahPesanan;
        
        if(totalHarga > 100000){
            totalHarga*=0.95;
        }
        
//        total.setText(String.format("Rp","%.2f",totalHarga));
        Total.setText(String.format("Rp %.2f", totalHarga));
        Total.setEditable(false);
        
        // Validasi input uang
        if (Cash.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan uang terlebih dahulu!");
            return;
        }

        // Menghitung kembalian
        try {
            double uangPembeli = Double.parseDouble(Cash.getText());
            double kembalian = uangPembeli - totalHarga;

            Kembalian.setText(String.format("Rp %.2f", kembalian));
            Kembalian.setEditable(false);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan jumlah uang yang valid!");
        }
    }//GEN-LAST:event_HitungActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
         buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        JumlahPesanan.setText("0");
        Cash.setText("");
        Kembalian.setText("");
        Total.setText("");
    }//GEN-LAST:event_ResetActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Keluar Dari Toko Rendy Bakery");
        System.exit(0);
    }//GEN-LAST:event_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TokoRoti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TokoRoti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TokoRoti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TokoRoti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TokoRoti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BlackForest;
    private javax.swing.JRadioButton BrownisKukus;
    private javax.swing.JRadioButton BuahCeri;
    private javax.swing.JTextField Cash;
    private javax.swing.JRadioButton Cheesake;
    private javax.swing.JRadioButton CokelatChips;
    private javax.swing.JButton Hitung;
    private javax.swing.JTextField JumlahPesanan;
    private javax.swing.JRadioButton KacangAlmond;
    private javax.swing.JRadioButton KejuParut;
    private javax.swing.JButton Keluar;
    private javax.swing.JTextField Kembalian;
    private javax.swing.JRadioButton KueCokelatLumer;
    private javax.swing.JRadioButton KueLapisLegit;
    private javax.swing.JButton Kurang;
    private javax.swing.JRadioButton NoTopping;
    private javax.swing.JRadioButton PuddingBuah;
    private javax.swing.JRadioButton RedVelvetCake;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Tambah;
    private javax.swing.JRadioButton Tiramisu;
    private javax.swing.JTextField Total;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
